wri/wri-terramatch-api

- app/Http/Controllers/V2/Projects/ViewMyProjectsController.php
Previously the endpoint that lists all the projects available for a given user, will take into consideration the organisation's projects as well.
With this PR, we are removing this behaviour as requested.
> fix: TM-527 remove organization projects on list

- app/Http/Controllers/AuthController.php
- app/Http/Controllers/V2/Projects/CreateProjectInviteController.php
There was a missing piece of logic that now we need to add a new user into the organization of the project that invited to monitor.
Commits: 
- fix: TM-538 add missing logic for users outside TM signing up
- fix: TM-538 deleted imports
> fix: TM-538 add new user to organisation after accept invite to monitoring project

- app/Console/Commands/CreateSpecificSiteReportCommand.php
Add command to generate site reports based on site's uuid. this command also update the corresponding task status to 'due'
[TM-530](https://gfw.atlassian.net/jira/software/c/projects/TM/issues/TM-530)
> feat: TM-530 add command to generate site reports for specific sites

- app/Http/Controllers/Traits/HandlesUpdateRequests.php
- app/Http/Controllers/V2/Nurseries/SubmitNurseryWithFormController.php
- app/Http/Controllers/V2/NurseryReports/SubmitNurseryReportWithFormController.php
- app/Http/Controllers/V2/ProjectReports/SubmitProjectReportWithFormController.php
- app/Http/Controllers/V2/Projects/SubmitProjectWithFormController.php
- app/Http/Controllers/V2/SiteReports/SubmitSiteReportWithFormController.php
- app/Http/Controllers/V2/Sites/SubmitSiteWithFormController.php
https://gfw.atlassian.net/browse/TM-595
FE PR: https://github.com/wri/wri-terramatch-website/pull/63
UpdateRequests weren't using the "draft" status that was defined on the model. The main implication of this is that when an update request was created or edited, it was automatically put into "awaiting approval", which meant it couldn't be edited further, and the "save and continue later" flow wasn't non-functional.
> [TM-595] Use the draft state in UpdateRequests.

- app/Models/V2/Projects/Project.php
https://gfw.atlassian.net/browse/TM-415
This turned out to be a very simple additional to what had already been done on this ticket. However, there is a great simplification that will take place as part of TM-560, once `Task` has a more robust `status` field, we'll be able to simply count the number of `tasks` in `due` or `needs-more-information` to calculate this, which will be much faster.
> [TM-415] Include unsubmitted tasks in the total_reporting_tasks attribute

- app/Console/Commands/MigrateTaskStatuses.php
- app/Console/Commands/Migration/CreateDueReportsMigrationCommand.php
- app/Console/Commands/Migration/CreateTasksMigrationCommand.php
- app/Exceptions/Handler.php
- app/Exceptions/InvalidStatusException.php
- app/Http/Controllers/V2/Projects/ViewProjectTasksController.php
- app/Http/Controllers/V2/Reports/SubmitReportWithFormController.php
- app/Http/Controllers/V2/Tasks/SubmitProjectTasksController.php
- app/Jobs/V2/CreateTaskDueJob.php
- app/Models/Traits/HasReportStatus.php
- app/Models/V2/Projects/Project.php
- app/Models/V2/ReportModel.php
- app/Models/V2/Tasks/Task.php
- app/Policies/V2/Tasks/TaskPolicy.php
- app/StateMachines/ReportStatusStateMachine.php
- app/StateMachines/TaskStatusStateMachine.php
https://gfw.atlassian.net/browse/TM-560
Note: this will merge into the epic. I'm simply basing the PR on the TM-561 feature branch to present a clean diff, as that one hasn't been approved and merged yet.
This body of work accomplishes two main things:
* Implements a state machine on Task's status column, similar to that on the reports in order to add some guardrails around valid transitions.
* Hooks into state machine transitions on the Report status to check if a task should automatically transition to a new status when a child report updates. This implements a lot of the required connections for this epic on the [Miro board](https://miro.com/app/board/uXjVNvvGBro=/)
> [TM-560] Task status states

- app/Console/Commands/FixReportCompletion.php
- app/Console/Commands/OneOff/FixReportCompletion.php
- app/Console/Commands/OneOff/MigrateTaskStatuses.php
- app/Console/Commands/OneOff/MigrateUpdateRequestStatuses.php
- app/Models/Traits/UsesLinkedFields.php
https://gfw.atlassian.net/browse/TM-427
Fixes several problems with the calculation of % complete on a report:
* `empty()` was used on boolean fields, but `false` is a valid answer, so switched to `is_null`
* Questions that store in the `answers` JSON field on the record were skipped entirely because it only considered linked field questions
* Questions that aren't even shown to the user were considered unanswered because the `show_on_parent_condition` value on the question wasn't considered
* Questions that aren't required were counted as a ding against the completed count.
The above meant that the % complete value could be wildly off, either too high or too low depending on the nature of the form.
> [TM-427] Fix the calculation of percent complete on a linked field entity

- app/Http/Controllers/V2/NurseryReports/NurseryReportsViaNurseryController.php
- app/Http/Controllers/V2/ProjectReports/ProjectReportsViaProjectController.php
- app/Http/Controllers/V2/SiteReports/SiteReportsViaSiteController.php
- app/Models/Traits/HasReportStatus.php
- app/Models/V2/Projects/Project.php
- app/Models/V2/Projects/ProjectReport.php
https://gfw.atlassian.net/browse/TM-740
There were a couple of problems:
* The number was wrong because the status refactor incorrectly removed `needs-more-information` reports from the calculation.
* The SQL was pretty inefficient. This could still be better with a subselect, but wiring that up in Laravel is tricky, and this at least gets the attribute calculation down to two queries.
> [TM-740] Fix up the calculation of the trees planted for a project.

- app/Models/V2/Projects/Project.php
- app/Models/V2/Sites/Site.php
https://gfw.atlassian.net/browse/TM-724
This had two problems:
* Similar to TM-740, it was skipping reports in needs-more-information state (a mistake in the status refactor)
* At the project level, it was fetching site reports using site ids, so the reports it was aggregating from were completely wrong.
I also improved the performance of this attribute calculation, similar to the work for 724.
> [TM-724] Fix aggregation of workday totals at the site and project level

- app/Jobs/GenerateApplicationExportJob.php
https://gfw.atlassian.net/browse/TM-779
The 12 hour time exports of Land Accelerator applications have been failing since Monday due to memory constraints. This same approach is used in some other export code, and should be safe. I also tested this same approach in the tinker console on prod to generate an up to date report.
> [TM-779] Allow application exports to run without memory limit.

- app/Jobs/V2/SendEntityStatusChangeEmailsJob.php
- app/Mail/EntityStatusChange.php
- app/Mail/Mail.php
- app/Models/Traits/HasEntityStatus.php
- app/Models/Traits/HasEntityStatusScopesAndTransitions.php
- app/Models/Traits/HasReportStatus.php
- app/Models/V2/EntityModel.php
- app/Models/V2/Nurseries/NurseryReport.php
- app/Models/V2/Projects/Project.php
- app/Models/V2/Projects/ProjectReport.php
- app/Models/V2/ReportModel.php
- app/Models/V2/Sites/SiteReport.php
- app/StateMachines/EntityStatusStateMachine.php
- app/StateMachines/ReportStatusStateMachine.php
- app/StateMachines/UpdateRequestStatusStateMachine.php
https://gfw.atlassian.net/browse/TM-702
This includes an update to isolate email sends on lower envs by setting an `EMAIL_RECIPIENTS` ENV variable. When set, all emails are sent to that list instead of to the originally intended recipient in order to avoid spamming real users from lower envs.
> [TM-702] Emails when entities and update requests move into approved or needs-more-information.

- app/Models/V2/Sites/SiteReport.php
https://gfw.atlassian.net/browse/TM-748
This method was removed accidentally in an earlier PR.
> [TM-748] re-instate ability to put site reports into the nothing to report state.

- app/Http/Controllers/V2/Exports/ExportAllMonitoredEntitiesController.php
https://gfw.atlassian.net/browse/TM-782
> TM-782 fix: change framework reference for exporting

- app/Console/Commands/Migration/RolesMigrationCommand.php
- app/Http/Controllers/V2/Exports/ExportAllMonitoredEntitiesController.php
- app/Models/V2/Projects/ProjectReport.php
- app/Models/V2/Workdays/Workday.php
- config/wri/linked-fields.php
- tests/V2/Exports/ExportAllMonitoredEntitiesControllerTest.php
https://gfw.atlassian.net/browse/TM-515
> [TM-812] Remove project establishment and seed collection from workday collections

- app/Http/Requests/V2/Forms/StoreFormRequest.php
- app/Http/Requests/V2/Forms/UpdateFormRequest.php
https://gfw.atlassian.net/browse/TM-950
This fix also included some manual data fixing in prod, but this was the underlying cause. The `collection` for linked field questions like tree species wasn't getting included in the form question, which meant that it wasn't getting included on the data sent to the server when tree species were edited.
> [TM-950] Allow the collection for linked fields to get stored in the DB form question

- openapi-src/V2/definitions/DashboardPolygonResponse.yml
- openapi-src/V2/definitions/FeatureCollection.yml
- openapi-src/V2/definitions/_index.yml
- openapi-src/V2/paths/Terrafund/get-v2-geojson-site.yml
- openapi-src/V2/paths/Terrafund/post-v2-terrafund-polygon.yml
- openapi-src/V2/paths/Terrafund/post-v2-terrafund-upload-geojson.yml
- openapi-src/V2/paths/Terrafund/post-v2-terrafund-upload-kml.yml
- openapi-src/V2/paths/Terrafund/post-v2-terrafund-upload-shapefile.yml
- openapi-src/V2/paths/Terrafund/put-v2-terrafund-site-polygon-uuid.yml
- openapi-src/V2/paths/_index.yml
- resources/docs/swagger-v2.yml
https://gfw.atlassian.net/browse/TM-850
> [TM-850] polygon functionality definition

- app/Http/Resources/V2/ProjectReports/ProjectReportResource.php
- app/Http/Resources/V2/SiteReports/SiteReportResource.php
- app/Models/V2/Projects/Project.php
- app/Models/V2/Projects/ProjectReport.php
- app/Models/V2/Sites/SiteReport.php
https://gfw.atlassian.net/browse/TM-911
This is the second time this work has gone into review; this time it's getting merged into the new release branch.
[FE PR](https://github.com/wri/wri-terramatch-website/pull/245)
> [TM-911] Update API responses for projects and sites and their reports to include seeding counts.

- app/Console/Kernel.php
- app/Http/Controllers/V2/TreeSpecies/GetTreeSpeciesForEntityController.php
- app/Http/Resources/V2/ProjectReports/ProjectReportResource.php
- app/Http/Resources/V2/SiteReports/SiteReportResource.php
- app/Jobs/V2/CreateTaskDueJob.php
- app/Models/V2/Projects/Project.php
- app/Models/V2/Projects/ProjectReport.php
- app/Models/V2/Sites/Site.php
- app/Models/V2/Sites/SiteReport.php
- config/wri/linked-fields.php
- database/migrations/2024_04_19_225021_create_workday_demographics.php
- database/migrations/2024_06_07_182710_retype_shared_drive_link.php
- database/migrations/2024_06_07_200450_add_anr_metrics_to_site_report.php
[Jira Release](https://gfw.atlassian.net/projects/TM/versions/10207/tab/release-report-all-issues)
[FE PR](https://github.com/wri/wri-terramatch-website/pull/254)
> [RELEASE] Incredible Iroko

- app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
To upload larger files that need more execution time, the limit is removed in upload endpoints.
> [TM-848] add execution limit to -1

- config/wri/permissions.php
* The Landscapes framework had never been added to the permissions file.
* The Enterprises framework was incorrectly specified in the permissions file.
> [TM-1103] Fix framework permissions

- app/Http/Controllers/V2/Exports/ExportAllMonitoredEntitiesController.php
https://gfw.atlassian.net/browse/TM-1262
What's going on here is that the FE used to get its list of frameworks for an API endpoint that returns access codes instead of slugs, but now it's coming from the list of slugs on the `auth/me` object. Slugs are the better thing to be passing around here, so I simply rolled back the change from April that supported access codes. This wasn't caught in testing because for most frameworks, the access code and the slug are the same. It was caught in prod because that's not true for TF Landscapes.
> [TM-1262] The string being passed in here is now the slug, not the access code.

- app/Console/Commands/OneOff/BackfillHidden.php
- app/Models/Interfaces/HandlesLinkedFieldSync.php
- app/Models/Traits/HasWorkdays.php
- app/Models/Traits/UsesLinkedFields.php
- app/Models/V2/Disturbance.php
- app/Models/V2/Invasive.php
- app/Models/V2/Projects/Project.php
- app/Models/V2/Projects/ProjectReport.php
- app/Models/V2/Seeding.php
- app/Models/V2/Sites/Site.php
- app/Models/V2/Sites/SiteReport.php
- app/Models/V2/Stratas/Strata.php
- app/Models/V2/TreeSpecies/TreeSpecies.php
- app/Models/V2/Workdays/Workday.php
- database/migrations/2024_09_03_222951_add_hidden_to_entity_associations.php
- tests/Unit/Models/V2/Workdays/WorkdayTest.php
https://gfw.atlassian.net/browse/TM-1263
We have a general data problem with entity-associated tables (tree species, seedings, workdays, etc): if a PD or admin going through the form fills in some data, and then changes their mind and clicks "no" to the conditional, thus hiding the field, the data is still recorded in the DB, and then gets included in attributes that aggregate that data into counts on the API response or in exports. 
We could just delete that data when the form is submitted, but if the user clicked "no" by accident, we want them to be able to recover it by going back and clicking "yes" without having the type the numbers in again. So, I've added a column to these tables (`hidden`), which gets set to true when the form is submitted and the conditional is set to "no". Then, …
> [TM-1263] Ignore hidden data

- app/Helpers/GeometryHelper.php
- app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
- app/Models/V2/Sites/SitePolygon.php
- app/Services/PolygonService.php
Adding site_id existence validator in creation of versions of polygons. 
If site_id dont exist will check if the site_id has the property to a existent site_id. 
This change of site_id will also preserve the status of previous version.
> [TM-1197] Add site id validator in upload

- app/Models/V2/Projects/Project.php
- database/migrations/2024_09_20_184711_add_landscape_to_v2_projects_table.php
To support the filter for the dashboard we need to add the single select field “landscape”
The options should be:
Kenya’s Greater Rift Valley
Ghana Cocoa Belt 
Lake Kivu and Rusizi River Basin
> [TM-1323] add migration for landscape in project

- app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php
- app/Jobs/Dashboard/RunActiveProjectsJob.php
- app/Services/Dashboard/RunActiveProjectsService.php
[Task Link](https://gfw.atlassian.net/browse/TM-1438)
> [TM-1438] add delayed job for active projects controller

- app/Jobs/SendDailyDigestNotificationsJob.php
- app/Jobs/V2/SendEntityStatusChangeEmailsJob.php
- app/Jobs/V2/SendReportReminderEmailsJob.php
- app/Models/Traits/SkipRecipientsTrait.php
[Task Link](https://gfw.atlassian.net/browse/TM-1423)
> [TM-1423] add conditional to skip recipients to monitoring partners

- app/Http/Resources/V2/ProjectReports/ProjectReportResource.php
- app/Http/Resources/V2/SiteReports/SiteReportResource.php
- app/Models/Traits/HasWorkdays.php
- app/Models/V2/Projects/ProjectReport.php
- app/Models/V2/Sites/SiteReport.php
- app/Models/V2/Workdays/Workday.php
[Task Link](https://gfw.atlassian.net/browse/TM-1352)
> [TM-1352] add logic to get new fields results

- app/Http/Controllers/V2/Projects/CreateProjectWithFormController.php
- app/Http/Resources/V2/Projects/ProjectResource.php
- app/Models/V2/Projects/Project.php
- config/wri/linked-fields.php
- database/migrations/2024_11_19_153800_add_field_project_establishment.php
[Task Link](https://gfw.atlassian.net/browse/TM-1472)
> [TM-1472] add direct seeding survival rate to project stablishment

- app/Helpers/GeometryHelper.php
- app/Models/V2/Sites/CriteriaSite.php
- app/Models/V2/Sites/CriteriaSiteHistoric.php
- app/Services/PolygonService.php
- database/migrations/2024_11_22_161557_remove_softdeletes_from_criteria_site.php
- database/migrations/2024_11_22_161611_create_criteria_site_historic_table.php
- database/migrations/2024_11_25_181031_remove_date_created_from_criteria_site.php
Remove useless attribute, need to run migration
> [TM-1503] criteria historic

- app/Http/Controllers/AuthController.php
- app/Http/Controllers/V2/User/AdminUserCreationController.php
- app/Http/Requests/SendLoginDetailsRequest.php
- app/Http/Requests/SetPasswordRequest.php
- app/Http/Requests/V2/User/AdminUserCreationRequest.php
- app/Jobs/SendLoginDetailsJob.php
- app/Mail/SendLoginDetails.php
- database/seeders/LocalizationKeysTableSeeder.php
- openapi-src/V2/definitions/AdminUserCreate.yml
- openapi-src/V2/definitions/_index.yml
- openapi-src/V2/paths/Auth/get-auth-mail.yml
- openapi-src/V2/paths/Auth/post-auth-reset.yml
- openapi-src/V2/paths/Auth/post-auth-send-login-details.yml
- openapi-src/V2/paths/Auth/post-auth-store.yml
- openapi-src/V2/paths/_index.yml
- resources/docs/swagger-v2.yml
- routes/api.php
- routes/api_v2.php
https://gfw.atlassian.net/browse/TM-1385
Frontend PR: https://github.com/wri/wri-terramatch-website/pull/706
> [TM-1385] Admin create user funtionality

- app/Http/Resources/V2/ProjectReports/ProjectReportResource.php
- app/Models/Traits/HasWorkdays.php
- app/Models/Traits/UsesLinkedFields.php
https://gfw.atlassian.net/browse/TM-1539
This change rolls back the previous patch and fixes the underlying issue with workday attributes.
> [TM-1539] Fix the underlying issue with workdays

- .github/workflows/pull-request.yml
- app/Console/Commands/ImportTreeSpeciesAssociations.php
- app/Models/V2/TreeSpecies/TreeSpecies.php
https://gfw.atlassian.net/browse/TM-1401
> [TM-1401] Import cleaned tree species associations.

- app/Console/Commands/ImportTreeSpeciesAssociations.php
- app/Console/Commands/OneOff/PopulateTreeSpeciesResearch.php
- app/Console/Commands/OneOff/UpdateTreeCollections.php
- app/Http/Resources/V2/TreeSpecies/TreeSpeciesResource.php
- config/wri/linked-fields.php
- database/migrations/2024_12_10_220655_add_infraspecific_epithet_to_tree_species_research.php
https://gfw.atlassian.net/browse/TM-1402
> [TM-1402] Updates to the v2_tree_species -> tree_species_research relationship

- app/Console/Commands/ImportTreeSpeciesAssociations.php
- app/Console/Commands/OneOff/PopulateTreeSpeciesResearch.php
The script took ~4 hours to run on staging last Friday. Hoping this can significantly speed that up and we need to run another insert test on staging anyway. Also fixed a problem in the import cleaned data script.
> [TM-1400] Do bulk inserts for a faster script execution.

- app/Http/Resources/V2/SiteReports/SiteReportResource.php
- app/Models/V2/Sites/SiteReport.php
- app/Models/V2/TreeSpecies/TreeSpecies.php
[Task Link](https://gfw.atlassian.net/browse/TM-1562)
> [TM-1562] update terrafund report pages

- app/Console/Commands/RecalculatePolygonAreas.php
- app/Helpers/PolygonGeometryHelper.php
- app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
- app/Services/AreaCalculationService.php
- app/Services/PolygonService.php
- docker/php.Dockerfile
- resources/python/polygon-area/app.py
- resources/python/polygon-indicator/tree_cover_indicator.py
- resources/python/polygon-voronoi/requirements.txt
https://gfw.atlassian.net/browse/TM-1467?focusedCommentId=35286
> [TM-1467] polygon area discrepancy

- app/Console/Commands/UpdateValuesForIndicatorsCommand.php
[Task Link](https://gfw.atlassian.net/browse/TM-1467)
> [TM-1467] dev monitoring indicators update command

- app/Services/RunIndicatorAnalysisService.php
- resources/python/gfw-area-adjustment/app.py
https://gfw.atlassian.net/browse/TM-1467?focusedCommentId=35430
> [TM-1467] Adjust GFW data areas with correction factor using ESRI:54009

- app/Models/V2/Projects/Project.php
https://gfw.atlassian.net/browse/TM-1585
> [TM-1585] add condition to filter approved sites

- app/Jobs/Dashboard/RunActiveCountriesTableJob.php
- app/Jobs/Dashboard/RunActiveProjectsJob.php
- app/Jobs/Dashboard/RunHectaresRestoredJob.php
- app/Jobs/Dashboard/RunJobsCreatedJob.php
- app/Jobs/Dashboard/RunTopTreesJob.php
- app/Jobs/Dashboard/RunTotalHeaderJob.php
- app/Jobs/Dashboard/RunTreeRestorationGoalJob.php
- app/Jobs/Dashboard/RunVolunteersAverageJob.php
- config/cache.php
https://gfw.atlassian.net/browse/TM-1586
> [TM-1586] set cache timeout for dashboard endpoints

- app/Http/Controllers/V2/Entities/GetRelationsForEntityController.php
- app/Http/Resources/V2/TreeSpecies/TreeSpeciesTransformer.php
- app/Models/V2/Projects/Project.php
- app/Models/V2/Sites/Site.php
https://gfw.atlassian.net/browse/TM-1603?focusedCommentId=36399
> [TM-1603] only data from approved reports

- routes/api_v2.php
This fixes an API route collision between the demographics fetch endpoints and the update request endpoint, which follows the same pattern.
> [TM-1681] Isolate the demographic types possible on this endpoint.

- app/Console/Commands/OneOff/FixUpdateRequestsJobsBeneficiaries.php
https://gfw.atlassian.net/browse/TM-1840
Project Report update requests on prod are currently broken because they still have the old style jobs / beneficiaries data embedded in them, but they need to have the newer style demographics data. So, this script crawls through the active update requests, collects the jobs / benes data from the old fields and builds the correct demographics format for them.
> [TM-1840] Update the data in older update requests on project reports

- app/Models/LandscapeGeom.php
- database/migrations/2025_01_27_002053_create_landscape_geom_table.php
- database/migrations/2025_04_15_170001_add_slug_to_landscape_geom.php
https://gfw.atlassian.net/browse/TM-1915
We'll eventually want to change `v2_projects` to use the `slug` instead of the name string, but that appears to be a pretty deep refactor, so for now, v3 is going to accept this `slug` and translate it to the name for the project query.
> [TM-1915] Add a required slug column to landscape_geom.

- app/Console/Commands/OneOff/CleanReportsConditionalDataAfterApproval.php
- app/Models/Traits/UsesLinkedFields.php
https://gfw.atlassian.net/browse/TM-1962
There were a couple of problems here:
* The default value for a form field that has been hidden is not some "empty" value (like `0`, `""` or `false`), it's null. Especially in the case of numerical fields, this has real consequences, as 0 can mean something quite different from null.
* There was a bug in the calculation for which form fields to clear out; it was using `$question` from the block above to pull the linked field key info, instead of `$child`.
* When an admin edits an already approved form, we want to apply the data cleaning right then, as there won't be the normal opportunity to do it later as part of the approval process.
I also updated the one off that runs the cleaning process on all approved reports to give better feedback and …
> [TM-1962] Clean conditional data admin edit

- app/Http/Resources/V2/Projects/ProjectResource.php
- app/Http/Resources/V2/Projects/ProjectWithAdminSchemaResource.php
- app/Models/V2/Projects/Project.php
- app/Models/V2/Projects/ProjectReport.php
/jobs-created uses demographics
/total-section-headeruses demographics. ( updated in this ticket ) 
getTotalJobsCreatedAttribute is erased from ProjectReport as it was not used anywhere. 
getTotalJobsCreatedAttribute is erased from Project and replaced to use getTotalApprovedJobsCreatedAttribute which get data from demographics. 
getTotalJobsCreatedAttribute and getTotalApprovedJobsCreatedAttribute were identical functions with different approach.
> [TM-2041] deprecate duplicated function. Keep jobs with demographics.
