app/Console/Commands/UpdateDueDateForReportsCommand.php

Include sites and nurseries report in command, previosly it only consider project reports.

Tm 547 site nursery reports due dates

---

app/Console/Commands/UpdateDueDateForReportsCommand.php

Merge changes done in branch TM-457 (pull request approved when merging to staging) into Master for deploying production.

Merge Staging (TM-547) to Master

---

app/Console/Commands/UpdateDueDateForReportsCommand.php
app/Models/V2/Projects/Project.php

modify reporting task counter functionality asked in [TM-415](https://gfw.atlassian.net/browse/TM-415)

Tm 415 reporting task counter

---

app/Console/Commands/UpdateUrlBucketCommand.php

add command to update reference path to s3 bucket.

fix: TM-556 update s3 bucket reference

---

app/Console/Commands/UpdateUrlBucketCommand.php

Update column name from cover_photo to thumbnail for Programmes table.

fix: TM-556 change column name for programmes table

---

app/Http/Resources/V2/ProjectReports/ProjectReportResource.php
app/Http/Resources/V2/SiteReports/SiteReportResource.php
app/Models/V2/Projects/ProjectReport.php
app/Models/V2/Sites/SiteReport.php
config/wri/linked-fields.php
database/migrations/2024_01_05_103014_add_column_paid_other_activity_description_pro_re.php
database/migrations/2024_01_05_105415_add_column_paid_other_activity_description_site_re.php

[Task Link](https://gfw.atlassian.net/browse/TM-470)

feat: TM-470 add new field description to project report and site report

---

app/Http/Controllers/V2/Projects/CreateProjectWithFormController.php
app/Http/Controllers/V2/Projects/SubmitProjectWithFormController.php

[Task Link](https://gfw.atlassian.net/browse/TM-520)
Creating another pull request, since the last one got mixed up

TM-520 create action track awaiting approval

---

app/Http/Controllers/V2/Projects/CreateProjectWithFormController.php
app/Http/Controllers/V2/Projects/SubmitProjectWithFormController.php

[Task Link](https://gfw.atlassian.net/browse/TM-520)

Tm 520/create action track awaiting approval

---

app/Console/Commands/CreateSpecificSiteReportCommand.php

Add function to restore soft-deleted task for new site reports

fix: TM-530 add trashed tasks for new site reports

---

app/Helpers/I18nHelper.php
app/Http/Controllers/V2/Forms/StoreFormController.php
app/Http/Controllers/V2/Forms/UpdateFormController.php
app/Http/Controllers/V2/FundingProgramme/AdminFundingProgrammeController.php

[Task Link](https://gfw.atlassian.net/browse/TM-577)

fix: TM-577 use i18n relationship in funding programmes

---

app/Models/V2/Projects/Project.php

change condition for reporting task counter TM 415

fix: TM-415 change condition for count

---

app/Console/Commands/FixReportCompletion.php

[TM-566](https://gfw.atlassian.net/browse/TM-566)

[TM-566] Created command to fix broken completion / completion_status data in historical completed reports

---

app/Models/Traits/UsesLinkedFields.php

[task link](https://gfw.atlassian.net/browse/TM-557)

feat: TM-557 conditional fields saving

---

app/Models/Traits/UsesLinkedFields.php

[task link](https://gfw.atlassian.net/browse/TM-557)

Tm 557 conditional fields not saving

---

app/Models/Traits/UsesLinkedFields.php

[task link](https://gfw.atlassian.net/browse/TM-557)

fix: TM-557 issue in the getAllAnswers's logic

---

app/Http/Controllers/V2/Organisations/OrganisationApproveUserController.php

[task link](https://gfw.atlassian.net/browse/TM-585)

feat: TM-585 add organization to the request to join an organization

---

app/Http/Controllers/V2/Forms/SubmitFormSubmissionController.php
app/Http/Controllers/V2/Forms/UpdateFormSubmissionController.php

[task link](https://gfw.atlassian.net/browse/TM-198)

feat: TM-198 admin panel - lastEdited date on applications are updating

---

app/Exports/V2/EntityExport.php

https://gfw.atlassian.net/browse/TM-575

feat: TM-575 add additional columns in prject, site and nursery reports

---

app/Exports/V2/EntityExport.php

https://gfw.atlassian.net/browse/TM-575

fix: TM-575 update values for exported reports

---

app/Exports/V2/EntityExport.php

add new columns based on ticket [TM-575](https://gfw.atlassian.net/browse/TM-575)

fix: TM-575 add new columns

---

app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php
routes/api_v2.php

[task link](https://gfw.atlassian.net/browse/TM-662)

Tm 662 implement total sections for terrafund dashboard header

---

app/Http/Controllers/V2/Dashboard/GetJobsCreatedController.php
routes/api_v2.php

https://gfw.atlassian.net/jira/software/c/projects/TM/issues/TM-664

feat: TM-664 add jobs created endpoint for dashboard

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
routes/api_v2.php

[task link](https://gfw.atlassian.net/browse/TM-668)

Tm 668 implement footer aggregate view for terrafund dashboard

---

app/Http/Controllers/V2/Dashboard/TopProjectsAndTopTreeSpeciesController.php
routes/api_v2.php

[task link](https://gfw.atlassian.net/browse/TM-667)

feat: TM-667 EndPoint for Top projects and Top Trees species added

---

app/Http/Controllers/V2/Entities/UpdateEntityWithFormController.php
app/Models/Traits/HasReportStatus.php
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-591

[TM-591] Admins no longer auto-accept entities that they edit.

---

app/Http/Controllers/V2/Forms/UpdateFormController.php

[Task Link](https://gfw.atlassian.net/browse/TM-687)

feat: TM-687 add field options to detailed intervention types

---

app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/TopProjectsAndTopTreeSpeciesController.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php
app/Http/Controllers/V2/Dashboard/VolunteersAndAverageSurvivalRateController.php

[Task Link](https://gfw.atlassian.net/browse/TM-662)
[Task Link](https://gfw.atlassian.net/browse/TM-665)
[Task Link](https://gfw.atlassian.net/browse/TM-668)
[Task Link](https://gfw.atlassian.net/browse/TM-667)

fix: endpoints logic improved

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php
app/Http/Controllers/V2/Dashboard/GetJobsCreatedController.php
app/Http/Controllers/V2/Dashboard/TopProjectsAndTopTreeSpeciesController.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php
app/Http/Controllers/V2/Dashboard/ViewRestorationStrategyController.php
app/Http/Controllers/V2/Dashboard/ViewTreeRestorationGoalController.php
app/Http/Controllers/V2/Dashboard/VolunteersAndAverageSurvivalRateController.php
app/Http/Resources/V2/Dashboard/ActiveCountriesTableResource.php
app/Http/Resources/V2/Dashboard/ActiveProjectsTableResource.php
app/Http/Resources/V2/Dashboard/JobsCreatedResource.php
app/Http/Resources/V2/Dashboard/TopProjectsAndTopTreeSpeciesResource.php
app/Http/Resources/V2/Dashboard/TotalSectionHeaderResource.php
app/Http/Resources/V2/Dashboard/ViewRestorationStrategyResource.php
app/Http/Resources/V2/Dashboard/ViewTreeRestorationGoalResource.php
app/Http/Resources/V2/Dashboard/VolunteersAndAverageResource.php

Add resource files to transform model data for dashboard endpoints.

Dashboard resources

---

app/Helpers/I18nHelper.php
app/Http/Controllers/V2/Forms/StoreFormController.php
app/Http/Controllers/V2/Forms/UpdateFormController.php

[Task Link](https://gfw.atlassian.net/browse/TM-682)

TM-682 form missing translations

---

resources/docs/swagger.yml

format swagger file for dashboard endpoints.

fix: format swagger file for dashboard endpoints

---

resources/docs/swagger.yml

add 'data' property for jobs created dashboard

fix: add data property for jobs created dashboard

---

app/StateMachines/TaskStatusStateMachine.php
app/StateMachines/UpdateRequestStatusStateMachine.php

https://gfw.atlassian.net/browse/TM-712

[TM-712] Fix submission of update requests.

---

app/Models/Traits/HasReportStatus.php
app/StateMachines/ReportStatusStateMachine.php

https://gfw.atlassian.net/browse/TM-715

[TM-715] Allow writing a report that had previously been marked as nothing to report

---

app/Models/Traits/HasEntityStatus.php
app/Models/V2/Nurseries/Nursery.php
app/Models/V2/Projects/Project.php
app/Models/V2/Sites/Site.php

https://gfw.atlassian.net/browse/TM-726

[TM-726] Fix use of state machines on non-report entities.

---

app/Models/Traits/UsesLinkedFields.php

https://gfw.atlassian.net/browse/TM-727

[TM-727] Fix form access for FormSubmissions.

---

app/Models/Traits/HasReportStatus.php

https://gfw.atlassian.net/browse/TM-728

[TM-728] Fix admins directly saving reports outside the normal approval flow

---

app/Models/V2/Tasks/Task.php
app/StateMachines/EntityStatusStateMachine.php
app/StateMachines/UpdateRequestStatusStateMachine.php

https://gfw.atlassian.net/browse/TM-686

[TM-686] A couple of fixes for the update request flow.

---

app/Http/Controllers/V2/Projects/CreateBlankProjectWithFormController.php
app/Http/Controllers/V2/Projects/CreateProjectWithFormController.php
app/Models/Traits/HasEntityStatus.php
app/Models/User.php

https://gfw.atlassian.net/browse/TM-729

[TM-729] Fix user associations when creating projects.

---

app/Http/Requests/V2/Forms/UpdateFormRequest.php

[Task Link](https://gfw.atlassian.net/browse/TM-733)

[TM-733] saving issue adding question

---

app/Http/Controllers/V2/Dashboard/CountriesController.php
app/Http/Controllers/V2/Dashboard/VolunteersAndAverageSurvivalRateController.php
app/Http/Resources/V2/Dashboard/CountriesResource.php
app/Http/Resources/V2/Dashboard/VolunteersAndAverageResource.php
resources/docs/swagger.yml
routes/api_v2.php

Add endpoint to countries for the header section

Add endpoint to countries

---

app/Http/Controllers/V2/Exports/ExportAllProjectDataAsProjectDeveloperController.php

https://gfw.atlassian.net/browse/TM-697

feat: TM-697 add Sites shapefiles in export for PD

---

app/Http/Controllers/V2/Exports/ExportProjectEntityAsProjectDeveloperController.php

https://gfw.atlassian.net/browse/TM-698

feat: TM-698 add shapefiles export option in export project entity

---

app/Http/Resources/V2/Sites/SiteResource.php
app/Models/V2/Sites/Site.php
config/wri/linked-fields.php
database/migrations/2024_03_11_132400_seed_options_list_siting_strategy.php
database/migrations/2024_03_11_132835_add_new_field_description_siting_strategy_to_v2_sites_table.php

[Task Link](https://gfw.atlassian.net/browse/TM-725)

feat: TM-725 add new fields to v2 sites

---

database/migrations/2024_03_12_161700_change_total_employees_column_type_to_organisation_table.php

[Task Link](https://gfw.atlassian.net/browse/TM-690)

feat: change total employees column type to organisation table

---

app/Http/Controllers/V2/Dashboard/ProjectProfileDetailsController.php
app/Http/Resources/V2/Dashboard/ProjectProfileDetailsResource.php
resources/docs/swagger.yml
routes/api_v2.php

endpoint for project profile details

feat: Add endpoint for projec profile section

---

app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php
app/Http/Resources/V2/Dashboard/ActiveProjectsTableResource.php
resources/docs/swagger.yml

add queryParams per_page and page to pagination

feat: add pagination to active projects endpoint

---

app/Http/Controllers/V2/Projects/ViewProjectTasksController.php
app/Http/Resources/V2/Projects/ProjectLiteResource.php
app/Models/V2/Projects/Project.php
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-705
FE: https://github.com/wri/wri-terramatch-website/pull/102

[TM-705] Minor API fixes needed for updated tasks page.

---

app/Helpers/TerrafundDashboardQueryHelper.php

add v2_projects.uuid in where clause to avoid ambiguous reference

fix: add project table for uuid

---

app/Http/Controllers/V2/Exports/ExportAllProjectDataAsProjectDeveloperController.php

[Task Link](https://gfw.atlassian.net/browse/TM-697)
This should fix the path used for storing temporal file before exporting

fix: use storage path for temporal file

---

resources/docs/swagger.yml

feat: add parameters per_page and page to active projects

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php

feat: query optimization

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php

feat: query optimization (#102)

---

app/Console/Commands/CreateBackdatedReportCommand.php

https://gfw.atlassian.net/browse/TM-769

feat: add project report generation in command

---

app/Jobs/V2/SendEntityStatusChangeEmailsJob.php
app/Mail/EntityStatusChange.php
app/Models/V2/Nurseries/NurseryReport.php
app/Models/V2/Projects/ProjectReport.php
app/Models/V2/Sites/SiteReport.php
composer.json
composer.lock

https://gfw.atlassian.net/browse/TM-702
This also gave me a nice excuse to fix up the relationship from reports -> project and organization, which has been bugging me because a) it was inefficient, and b) the return type was `BelongTo`, but it was possible to get a `null` instead.

[TM-702] Addressing product feedback in entity update emails.

---

app/Exports/V2/BaseExportFormSubmission.php

https://gfw.atlassian.net/browse/TM-823

TM-823 feat: add type in export form submission

---

app/Helpers/I18nHelper.php

[Task Link](https://gfw.atlassian.net/browse/TM-746)

[TM-746] fix: validate length of short values 255 chars limit

---

app/Policies/V2/Projects/ProjectPolicy.php

https://gfw.atlassian.net/browse/TM-798

[TM-798] Given a project UUID, the Greenhouse service account can read the project information and all site information.

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php

mismatch between header job totals and tracker job totals

Tm 815 mismatch between header job totals and tracker job totals

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php

https://gfw.atlassian.net/browse/TM-810

TM-810 fix: amount consistency in jobs created

---

app/Http/Controllers/V2/Dashboard/ViewTreeRestorationGoalController.php

get the latest site report to sum the number of tree species

fix: get the latest site report to sum the number of tree species

---

app/Exceptions/Handler.php

https://gfw.atlassian.net/browse/TM-792

[TM-792] Log Sentry errors in staging as well.

---

app/Http/Controllers/V2/Dashboard/ViewRestorationStrategyController.php
app/Http/Resources/V2/Dashboard/ViewRestorationStrategyResource.php
resources/docs/swagger.yml

add land tenures to restoration strategy endpoint

add land tenures to endpoint

---

database/migrations/2024_01_08_160230_seed_options_list_siting_strategy.php
database/migrations/2024_03_11_132400_seed_options_list_siting_strategy.php

change migrations to anonymous class

fix: change migrations to anonymous class

---

app/Http/Controllers/V2/Dashboard/TopProjectsAndTopTreeSpeciesController.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php

fixes to getTotalTreesRestoredSum and  getTopProjects functions

fix: fixes to getTotalTreesRestoredSum and  getTopProjects functions

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php
app/Http/Controllers/V2/Dashboard/VolunteersAndAverageSurvivalRateController.php

fix: fixes to functions performed

---

app/Http/Controllers/V2/Dashboard/ViewTreeRestorationGoalController.php

add comlpete sum of trees planted.

add total trees plantedn and not the latest reported

---

routes/api.php

https://gfw.atlassian.net/browse/TM-830

[TM-830] User create needs to be unprotected.

---

app/Http/Controllers/V2/Dashboard/TopProjectsAndTopTreeSpeciesController.php

fix: change logic to top 20 tree species planted

---

app/Http/Controllers/V2/Dashboard/ViewTreeRestorationGoalController.php

fix: update to get consistency data in trees planted by period endpoint

fix: update to get consistency data in trees planted by period endpoint

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php
app/Http/Controllers/V2/Dashboard/GetJobsCreatedController.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php
app/Http/Controllers/V2/Dashboard/VolunteersAndAverageSurvivalRateController.php

Reverts wri/wri-terramatch-api#132

Revert "fix: jobs created"

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
routes/api_v2.php

Please check if your PR fulfills the following requirements:
Please check the type of change your PR introduces:
Issue Number: N/A
-
-
-

Editgeometry

---

app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php

Please check if your PR fulfills the following requirements:
Please check the type of change your PR introduces:
Issue Number: N/A
-
-
-

add update geometry

---

app/Http/Controllers/V2/Sites/CreateSiteWithFormController.php

feat: add old_id

---

.gitignore
app/Console/Commands/Migration/RolesMigrationCommand.php
app/Exceptions/Handler.php
app/Http/Controllers/V2/Files/UploadController.php
app/Http/Middleware/ModelInterfaceBindingMiddleware.php
app/Http/Requests/V2/File/BulkUploadRequest.php
app/Models/V2/Forms/Form.php
app/Models/V2/Forms/FormQuestionOption.php
app/Models/V2/FundingProgramme.php
app/Models/V2/MediaModel.php
app/Models/V2/Nurseries/Nursery.php
app/Models/V2/Nurseries/NurseryReport.php
app/Models/V2/Organisation.php
app/Models/V2/ProjectPitch.php
app/Models/V2/Projects/Project.php
app/Models/V2/Projects/ProjectMonitoring.php
app/Models/V2/Projects/ProjectReport.php
app/Models/V2/Sites/Site.php
app/Models/V2/Sites/SiteMonitoring.php
app/Models/V2/Sites/SiteReport.php
app/Policies/V2/Sites/SitePolicy.php
app/functions.php
config/wri/file-handling.php
database/factories/UserFactory.php
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php
tests/V2/Files/UploadControllerTest.php

https://gfw.atlassian.net/browse/TM-803
Along the way I made the model interface binding middleware a little more flexible and a little easier to use.

[TM-803] Upload bulk photo upload to sites for Greenhouse.

---

app/Http/Controllers/V2/Files/UploadController.php
app/Http/Controllers/V2/MediaController.php
database/migrations/2024_04_19_190707_add_created_by_to_media_table.php
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php
tests/V2/Files/UploadControllerTest.php
tests/V2/MediaControllerTest.php

https://gfw.atlassian.net/browse/TM-804

[TM-804] Media bulk deletion

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php
app/Http/Controllers/V2/Dashboard/TopProjectsAndTopTreeSpeciesController.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php
app/Http/Controllers/V2/Dashboard/ViewTreeRestorationGoalController.php

https://gfw.atlassian.net/browse/TM-885

TM-885 fix: get trees planted count consistency

---

app/Console/Commands/Migration/AddNumericValuesCommand.php
app/Http/Controllers/V2/Dashboard/CountryDataController.php
app/Http/Controllers/V2/Dashboard/GetProjectsController.php
app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/functions.php
database/migrations/2024_04_22_145957_add_user_geospatial_fields.php
database/migrations/2024_04_22_215000_add_column_lat_and_long_to_v2_project_table.php
resources/docs/swagger.yml
routes/api_v2.php

Please check if your PR fulfills the following requirements:
Please check the type of change your PR introduces:
Issue Number: N/A
-
-
-

Bboxcountry

---

app/Http/Controllers/V2/Sites/SitePolygonDataController.php
resources/docs/swagger-v2.yml
routes/api_v2.php

add endpoint to get sites polygon data

feat: add endpoint to get sites polygon data

---

app/Http/Controllers/V2/Sites/SitePolygonDataController.php
resources/docs/swagger-v2.yml
routes/api_v2.php

endpoint to get bbox for sites based in the uuid

add endpoint to get bbox for sites

---

app/Http/Controllers/V2/Dashboard/CountryDataController.php
app/Models/V2/Projects/Project.php
resources/docs/swagger.yml
routes/api_v2.php

add points endpoint to tooltip project and alter model of projects to have all relations and counts

Pointsdatatooltip

---

app/Console/Commands/OneOff/MigrateWorkdayData.php
app/Console/Commands/ReportWorkdayDiscrepancies.php
app/Models/V2/Workdays/Workday.php
app/Models/V2/Workdays/WorkdayDemographic.php
database/migrations/2024_04_19_225021_create_workday_demographics.php
database/migrations/2024_04_25_222046_add_migrated_to_workday.php

https://gfw.atlassian.net/browse/TM-877

[TM-877] New Workday DB structure and migration

---

app/Http/Controllers/V2/Dashboard/CountryDataController.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php
app/Http/Controllers/V2/Sites/SitePolygonDataController.php
app/Http/Resources/V2/Dashboard/TotalSectionHeaderResource.php

Countrynameforheader

---

app/Http/Controllers/V2/User/AdminUserController.php
app/Http/Requests/V2/User/UpdateUserRequest.php
app/Http/Resources/V2/User/UserResource.php
app/Models/V2/User.php

Add country and program fields to users table

feat: add country and program

---

app/Helpers/GeometryHelper.php
app/Http/Controllers/V2/Dashboard/GetPolygonsController.php
app/Http/Controllers/V2/Sites/SitePolygonDataController.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
resources/docs/swagger-v2.yml
routes/api_v2.php

feat: add geojson download definition on swagger v2

feat: add geojson download definition on swagger v2

---

app/Http/Controllers/UsersRoleController.php
app/Http/Controllers/V2/Dashboard/ViewProjectController.php
app/Resources/UserRoleResource.php
app/Validators/UserRoleValidator.php
resources/docs/swagger.yml

fix: fixes

---

resources/docs/swagger-v2.yml

add definition in swagger to get polygon data

add definition in swagger to get polygon data

---

app/Console/Commands/MergeEntities.php
app/Models/V2/Sites/Site.php
app/Models/V2/TreeSpecies/TreeSpecies.php
config/wri/entity-merge-mapping.php

https://gfw.atlassian.net/browse/TM-836
For now it can only handle Terrafund Sites (and their reports), but it was built in a way that makes it easy to expand to other entities and frameworks in the future as needed.

[TM-836] Merge entities tool

---

app/Http/Controllers/V2/ProjectPipeline/DeleteProjectPipelineController.php
app/Http/Controllers/V2/ProjectPipeline/GetProjectPipelineController.php
app/Http/Controllers/V2/ProjectPipeline/StoreProjectPipelineController.php
app/Http/Controllers/V2/ProjectPipeline/UpdateProjectPipelineController.php
app/Http/Requests/V2/StoreProjectPipelineRequest.php
app/Http/Requests/V2/UpdateProjectPipelineRequest.php
app/Http/Resources/V2/ProjectPipelineResource.php
app/Models/V2/ProjectPipeline.php
database/migrations/2024_04_29_155000_create_project_pipeline_table.php
resources/docs/swagger-v2.yml
resources/docs/swagger.yml
routes/api_v2.php

Add endpoint and methods to project pipeline

feat: add endpoints to project pipeline

---

app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php

Add function to total hectares

feat: add function to total hectares

---

app/Http/Controllers/V2/AuditStatus/DeleteAuditStatusController.php
app/Http/Controllers/V2/AuditStatus/GetAuditStatusController.php
app/Http/Controllers/V2/AuditStatus/StoreAuditStatusController.php
app/Http/Controllers/V2/AuditStatus/UpdateAuditStatusController.php
app/Http/Requests/V2/StoreAuditStatusRequest.php
app/Http/Requests/V2/UpdateAuditStatusRequest.php
app/Http/Resources/V2/AuditStatusResource.php
app/Models/V2/AuditStatus/AuditAttachment.php
app/Models/V2/AuditStatus/AuditStatus.php
database/migrations/2024_05_08_130000_create_attachment_table.php
database/migrations/2024_05_08_130000_create_status_table.php
resources/docs/swagger-v2.yml
routes/api_v2.php

add endpoint and swagger to audits status

feat: add endpoint and swagger to audits status

---

app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php

fix: get project id with site and project tables

fix: get project id with site and project tables

---

app/Http/Controllers/V2/Geometry/GeometryController.php
app/Validators/SitePolygonValidator.php
openapi-src/V2/definitions/SiteGeometryPost.yml
openapi-src/V2/paths/Geometry/post-v2-geometry-validate.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-800

[TM-800] GH polygon validation endpoint implemented.

---

app/Http/Controllers/V2/Geometry/GeometryController.php
app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
app/Models/V2/PolygonGeometry.php
app/Models/V2/Sites/SitePolygon.php
app/Policies/V2/PolygonGeometryPolicy.php
app/Services/PolygonService.php
database/migrations/2024_05_10_215235_add_created_by_to_geometry_tables.php
openapi-src/V2/paths/Geometry/delete-v2-geometry.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-801
In addition to the deletion of polygons, the first commit on this PR implements created_by tracking for `PolygonGeometry` and `SitePolygon`

[TM-801] Greenhouse polygon delete endpoint

---

app/Http/Controllers/V2/Geometry/GeometryController.php
app/Models/V2/PolygonGeometry.php
app/Models/V2/Sites/CriteriaSite.php
app/Policies/V2/PolygonGeometryPolicy.php
app/Services/PolygonService.php
openapi-src/V2/paths/Geometry/put-v2-geometry-uuid.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-802

[TM-802] Greenhouse polygon update endpoint

---

app/Console/Commands/Migration/RolesMigrationCommand.php
app/Policies/FrameworkPolicy.php
app/Policies/V2/FundingProgrammePolicy.php
app/Policies/V2/Nurseries/NurseryPolicy.php
app/Policies/V2/Nurseries/NurseryReportPolicy.php
app/Policies/V2/Projects/ProjectPolicy.php
app/Policies/V2/Projects/ProjectReportPolicy.php
app/Policies/V2/Sites/SitePolicy.php
app/Policies/V2/Sites/SiteReportPolicy.php
app/Policies/V2/Tasks/TaskPolicy.php
app/Policies/V2/UpdateRequests/UpdateRequestPolicy.php
config/wri/permissions.php

https://gfw.atlassian.net/browse/TM-904
[FE PR](https://github.com/wri/wri-terramatch-website/pull/163)

[TM-904] Add HBF as a framework permission and admin type.

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
openapi-src/V2/definitions/V2TerrafundCriteriaData.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/Terrafund/get-v2-terrafund-validation-criteria-data.yml
openapi-src/V2/paths/Terrafund/get-v2-terrafund-validation-polygon.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

feat: add endpoint for polygon validation

feat: add endpoint for polygon validation

---

app/Http/Controllers/V2/ReportingFrameworks/AdminCreateReportingFrameworkController.php

https://gfw.atlassian.net/browse/TM-930

[TM-930] Don't attempt to create a permission that already exists.

---

app/Http/Controllers/V2/Projects/ViewProjectSitesController.php
app/Http/Controllers/V2/Sites/AdminIndexSitesController.php

https://gfw.atlassian.net/browse/TM-674

[TM-674] Site ids searchable

---

app/Console/Commands/OneOff/MigrateWorkdayOtherDescription.php
app/Exports/V2/BaseExportFormSubmission.php
app/Exports/V2/EntityExport.php
app/Helpers/CustomFormHelper.php
app/Models/Traits/HasWorkdays.php
app/Models/V2/Projects/ProjectReport.php
app/Models/V2/Sites/SiteReport.php
app/Models/V2/Workdays/Workday.php
tests/V2/ProjectReports/UpdateProjectReportWithFormControllerTest.php

https://gfw.atlassian.net/browse/TM-931

[TM-931] Handle the new location of other description and workdays data structure in exports

---

app/Helpers/GeometryHelper.php
app/Helpers/TerrafundDashboardQueryHelper.php

fix issues after removing project_id column from site_polygon table

fix issues after removing project_id column from site_polygon table

---

app/Exports/V2/EntityExport.php
app/Models/V2/Projects/ProjectReport.php

https://gfw.atlassian.net/browse/TM-680

[TM-680] Include sum of total seedlings grown to date in project report rows.

---

app/Models/V2/FundingProgramme.php

fix duplicate property error "uuid"

fix: fix/duplicate-property-error

---

app/Http/Controllers/V2/AuditStatus/StoreAuditStatusController.php
app/Models/Traits/SaveAuditAttachmentTrait.php
app/Models/V2/AuditAttachment/AuditAttachment.php
database/migrations/2024_05_20_113300_add_new_field_url_to_attachment_table.php

feat: charge files to s3

---

database/migrations/2024_05_14_151653_create_point_geometry_table.php

feat: migration to add Point Geometry Table

feat: migration to add Point Geometry Table

---

app/Http/Controllers/V2/Projects/AdminProjectsUpdateStatusController.php
app/Http/Controllers/V2/Sites/AdminSitePolygonsUpdateStatusController.php
app/Http/Controllers/V2/Sites/AdminSitesUpdateStatusController.php

Add conditional to entities update

feat: add conditional is_activve -> true

---

app/Exports/V2/EntityExport.php

https://gfw.atlassian.net/browse/TM-928

[TM-928] Include a link to the TM Admin view of sites, nurseries, site reports and nursery reports in export.

---

app/Mail/FormSubmissionRejected.php

https://gfw.atlassian.net/browse/TM-889

[TM-898] Update application rejection email copy.

---

database/migrations/2024_05_21_193901_float_regeneration.php

https://gfw.atlassian.net/browse/TM-738

[TM-738] Support fewer than 0 for "A natural regeneration"

---

database/migrations/2024_05_14_151653_create_point_geometry_table.php

feat: create Point Geometry table

[TM-919] feat: create Point Geometry table

---

app/Http/Controllers/V2/AuditStatus/GetAuditStatusProjectPolygonsController.php
app/Http/Resources/V2/AuditStatusProjectPolygonsResource.php
resources/docs/swagger-v2.yml
routes/api_v2.php

add project polygons controller to audit status

feat: add project polygons controller to audit status

---

app/Http/Resources/V2/Sites/SiteResource.php

https://gfw.atlassian.net/browse/TM-738
This covers a case I missed in the original ticket description.

[TM-738] For the UI, round values greater than 1 to a whole int.

---

app/Models/V2/Projects/Project.php
app/Models/V2/Sites/Site.php
database/factories/V2/Workdays/WorkdayFactory.php
tests/Unit/Models/V2/Projects/ProjectTest.php
tests/Unit/Models/V2/Sites/SiteTest.php

https://gfw.atlassian.net/browse/TM-938

[TM-938] Aggregate demographics for the site and project workday_count attributes

---

app/Http/Controllers/V2/Dashboard/GetProjectsController.php

Filter projects by lat and long

feat: filter projects by lat and long

---

app/Http/Controllers/V2/AuditStatus/GetAuditStatusController.php
app/Http/Requests/V2/StoreAuditStatusRequest.php
app/Http/Requests/V2/UpdateAuditStatusRequest.php
app/Models/Traits/SaveAuditStatusTrait.php
app/Models/V2/AuditAttachment/AuditAttachment.php
app/Models/V2/AuditStatus/AuditStatus.php
database/migrations/2024_05_27_130000_drop_column_attachment_url_form_status_table.php
resources/docs/swagger-v2.yml

feat:  remove attachment_url column

---

resources/docs/swagger-v2.yml

add AuditStatusResponseWithData to swagger

feat: add AuditStatusResponseWithData to swagger

---

app/Http/Resources/V2/Projects/ProjectResource.php
app/Http/Resources/V2/Sites/SiteResource.php
app/Models/V2/Projects/Project.php
app/Models/V2/Sites/Site.php

https://gfw.atlassian.net/browse/TM-938
[FE PR](https://github.com/wri/wri-terramatch-website/pull/220)

[TM-938] Send both the old count and the new count to the client as separate fields

---

openapi-src/V2/definitions/ProjectPipeline.yml
openapi-src/V2/definitions/RoleUserCreate.yml
openapi-src/V2/definitions/RoleUserRead.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/ProjectPipeline/get-v2-project-pipeline.yml
openapi-src/V2/paths/Users/post-users-register.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml

add missing swagger definitions for dashboard

add missing swagger definitions for dashboard

---

app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Controllers/V2/Dashboard/GetPolygonsController.php
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

add endpoint to get polygons by status for given project

add endpoint to get polygons by status for given project

---

app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Controllers/V2/Dashboard/GetPolygonsController.php
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

add endpoint to get bbox for projects

add endpoint to get bbox for projects

---

app/Http/Resources/V2/ProjectReports/ProjectReportResource.php
app/Http/Resources/V2/SiteReports/SiteReportResource.php
app/Models/V2/Projects/Project.php
app/Models/V2/Projects/ProjectReport.php
app/Models/V2/Sites/SiteReport.php

https://gfw.atlassian.net/browse/TM-911
[FE PR](https://github.com/wri/wri-terramatch-website/pull/235)

[TM-911] Update API responses for projects and sites and their reports to include seeding counts.

---

app/Validators/Extensions/Polygons/FeatureBounds.php

Change to receive multipolygon in uploads

[TM-848] fix for multipolygons validation

---

app/Helpers/GeometryHelper.php

prevent bbox without polygons values

Add validator to no return big bbox

---

database/migrations/2024_06_07_182710_retype_shared_drive_link.php

https://gfw.atlassian.net/browse/TM-965

[TM-965] Retype the shared_drive_link columns in order to remove the 255 character limit.

---

app/Models/V2/Projects/Project.php
app/Models/V2/Sites/Site.php
app/Models/V2/Sites/SiteReport.php
config/wri/linked-fields.php
database/migrations/2024_06_07_200450_add_anr_metrics_to_site_report.php

https://gfw.atlassian.net/browse/TM-940

[TM-940] Support a new field on site reports to collect metrics on tree regeneration

---

app/Console/Kernel.php

https://gfw.atlassian.net/browse/TM-970

[TM-970] Stop trying to call a script that doesn't exist.

---

app/Console/Kernel.php
app/Jobs/V2/CreateTaskDueJob.php

https://gfw.atlassian.net/browse/TM-939

[TM-939] Update timing of PPC report generation.

---

app/Http/Controllers/V2/Sites/SiteCheckApproveController.php
openapi-src/V2/definitions/SiteCheckApproveResponse.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/Sites/get-v2-sites-uuid-check-approve.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

[Task Link](https://gfw.atlassian.net/browse/TM-843)
An endpoint to check wether all `SitePolygon` s for a given site are approved.

[TM-843] add endpoint to determine wether a site can be approved

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php

https://gfw.atlassian.net/browse/TM-886
This commit implements sys_get_temp_dir for all uploaded files related to polygons.

[TM-886] implement sys_get_temp_dir for upload files

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php

Move upload files to tmp location

Tm 886 upload files to temporary

---

app/Http/Controllers/V2/TreeSpecies/GetTreeSpeciesForEntityController.php

https://gfw.atlassian.net/browse/TM-754

[TM-754] Respect the filter query param on the tree species API

---

database/migrations/2024_04_19_225021_create_workday_demographics.php

https://gfw.atlassian.net/browse/TM-983

[TM-961] verify existence of workday_demographics table in migration

---

app/Http/Controllers/V2/Dashboard/ProjectProfileDetailsController.php
app/Http/Resources/V2/Dashboard/ProjectProfileDetailsResource.php
app/Models/V2/Projects/Project.php
openapi-src/V2/definitions/DashboardProjectProfileData.yml
resources/docs/swagger-v2.yml

add cover_image property to project

feat: add cover_image property

---

app/Services/PythonService.php
docker/php.Dockerfile
resources/python/polygon-voronoi/app.py
resources/python/polygon-voronoi/requirements.txt

Adds a service to access the Python voronoi transformation script. Note: in order for this to work locally, the following steps are needed:
* Take backup of the local db:
*  docker-compose exec -T mariadb mysql -h localhost -u wri -pwri wri_restoration_marketplace_api > db-backup.sql
* docker-compose down
* make rebuild-with-composer 
* make up
* Restore local DB
*  docker-compose exec -T mariadb mysql -h localhost -u root -proot wri_restoration_marketplace_api < db-backup.sql
https://gfw.atlassian.net/browse/TM-962
I added the one-line needed in the php dockerfile for https://gfw.atlassian.net/browse/TM-974 as well.
I should note too that the script should be executed in the `PolygonService` like so:
```
$polygonGeojson = App::make(PythonService::class)->voronoiTransformation($geojson) …
```

[TM-962] Voronoi script

---

app/Console/Commands/CreateReportCommand.php

https://gfw.atlassian.net/browse/TM-987

[TM-987] Enhance the create report tool to accept a due date and generate reports for child models of Project.

---

app/Helpers/GeometryHelper.php
routes/api_v2.php

fix after merge overwrites controller

[TM-874] relocate view project controller

---

config/wri/linked-fields.php
database/migrations/2024_06_20_215908_add_project_report_fields.php

https://gfw.atlassian.net/browse/TM-975

[TM-975] Add three new fields to project report.

---

app/Http/Controllers/V2/Auditable/UpdateAuditableStatusController.php

https://gfw.atlassian.net/browse/TM-847

[TM-847] convert criteriaList to array

---

app/Http/Controllers/V2/Forms/FormOptionsLabelController.php
app/Http/Resources/V2/Forms/FormQuestionOptionResource.php

[Task Link](https://gfw.atlassian.net/browse/TM-984)

[TM-984] fix: change logic to formOptionsLabelController reponse

---

app/Http/Controllers/V2/Projects/CreateProjectWithFormController.php
app/Models/V2/Projects/Project.php
config/wri/linked-fields.php
database/migrations/2024_06_20_221015_add_fields_project_establishment.php

https://gfw.atlassian.net/browse/TM-971

[TM-971] Add a set of new fields for project establishment.

---

app/Exports/V2/EntityExport.php

https://gfw.atlassian.net/browse/TM-989

[TM-989] Include update request status in entity exports

---

app/Http/Controllers/AuthController.php
app/Http/Controllers/V2/Projects/CreateProjectInviteController.php
app/Mail/V2ProjectInviteReceived.php
tests/V2/Projects/CreateProjectInviteControllerTest.php

https://gfw.atlassian.net/browse/TM-915
[FE PR](https://github.com/wri/wri-terramatch-website/pull/280)

[TM-915] Create the user record when a non-existent users is added as a monitoring partner

---

app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
openapi-src/V2/paths/Terrafund/get-api-v2-terrafund-polygon-uuid.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-1000

[TM-1000] add site name to tooltip

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
openapi-src/V2/definitions/V2TerrafundCriteriaSite.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-1002

[TM-1002] add non valid criteria in validation site endpoint

---

app/Services/PolygonService.php

https://gfw.atlassian.net/browse/TM-1002

[TM-1002] remove validation when creating geojson models records

---

app/Http/Controllers/V2/Polygons/ChangeStatusPolygonsController.php
app/Models/V2/Sites/SitePolygon.php

fix change getclass to polygon

fix change getclass to polygon

---

app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Controllers/V2/Dashboard/ViewProjectController.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
app/Services/PolygonService.php

https://gfw.atlassian.net/browse/TM-1045

[TM-1045] assign draft on create

---

app/Clients/GreenhouseClient.php
app/Http/Controllers/V2/MediaController.php
app/Jobs/NotifyGreenhouseJob.php
app/Observers/MediaObserver.php
app/Observers/SitePolygonObserver.php
app/Providers/AppServiceProvider.php
config/services.php

https://gfw.atlassian.net/browse/TM-1031

[TM-1031] Notify Greenhouse when polygons are updated or media is deleted.

---

app/Console/Commands/RemoveDuplicatedReportsCommand.php

[Task Link](https://gfw.atlassian.net/browse/TM-1068)

[TM-1068] feat: add new command to remove duplicates reports to entity

---

app/Http/Controllers/V2/Geometry/GeometryController.php
app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
app/Models/V2/Sites/SitePolygon.php
app/Services/PolygonService.php
database/migrations/2024_07_01_144528_add_column_source_site_polygon_table.php
openapi-src/V2/definitions/SitePolygon.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-1022

[TM-1022] polygon source

---

database/migrations/2024_07_01_144528_add_column_source_site_polygon_table.php

https://gfw.atlassian.net/browse/TM-1022

[TM-1022] verify existence of source column

---

app/Http/Controllers/V2/Forms/FormOptionsLabelController.php

[Task Link](https://gfw.atlassian.net/browse/TM-984)

[TM-984]fix: improve logic to call image property

---

app/Http/Controllers/V2/Entities/SubmitEntityWithFormController.php
app/Http/Controllers/V2/UpdateRequests/AdminStatusUpdateRequestController.php
app/Models/Traits/SaveAuditStatusTrait.php
database/migrations/2024_07_02_010623_alter_audit_statuses_table_type_column.php
tests/V2/UpdateRequests/AdminStatusUpdateRequestControllerTest.php

[Task Link](https://gfw.atlassian.net/browse/TM-952)

[TM-952] implement updated change request

---

database/migrations/2024_07_02_160257_add_columns_lat_long_to_v2_projects_table.php

https://gfw.atlassian.net/browse/TM-1077

[TM-1077] Add latitude and longitude columns to v2_projects table

---

app/Policies/AuthPolicy.php
app/functions.php

[Task Link](https://gfw.atlassian.net/browse/TM-1025)

[TM-1025] add isNewRoleUser to me function

---

app/StateMachines/SiteStatusStateMachine.php

[Task Link](https://gfw.atlassian.net/browse/TM-951)

[TM-951] add status dependencies

---

app/Http/Controllers/V2/Projects/CreateProjectWithFormController.php
app/Models/V2/Projects/Project.php
config/wri/linked-fields.php
database/migrations/2024_06_20_215908_add_project_report_fields.php
database/migrations/2024_06_20_221015_add_fields_project_establishment.php

https://gfw.atlassian.net/projects/TM/versions/10225/tab/release-report-all-issues

[RELEASE] Incredible Iroko Hotfix 2024 07 03

---

app/Models/V2/Sites/Site.php

https://gfw.atlassian.net/browse/TM-1093

[TM-1093] Sites in restoration-in-progress need to count as approved.

---

app/Models/V2/Projects/Project.php
app/Models/V2/Sites/Site.php

https://gfw.atlassian.net/projects/TM/versions/10227/tab/release-report-all-issues

[RELEASE] Hotfix JJ 2024 07 09

---

app/Http/Controllers/V2/Entities/AdminStatusEntityController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1099)

[TM-1099] update site status to restoration-in-progress

---

app/Models/V2/Projects/ProjectReport.php

https://gfw.atlassian.net/browse/TM-1100

[TM-1100] Make the new fields fillable.

---

app/Services/PolygonService.php

[Task Link](https://gfw.atlassian.net/browse/TM-951?focusedCommentId=28968)

[TM-951] fix dependency status for greenhouse polygon

---

app/Http/Controllers/V2/Entities/AdminStatusEntityController.php
app/StateMachines/SiteStatusStateMachine.php

[Task Link](https://gfw.atlassian.net/browse/TM-1099)

[TM-1099] update site status

---

app/Http/Controllers/V2/Entities/AdminStatusEntityController.php
app/Models/V2/Projects/ProjectReport.php
app/Services/PolygonService.php
app/StateMachines/SiteStatusStateMachine.php

https://gfw.atlassian.net/projects/TM/versions/10228/tab/release-report-all-issues

[RELEASE] Hotfix JJ 2024 07 10

---

app/Http/Controllers/V2/Projects/DeleteProjectMonitoringPartnersController.php
openapi-src/V2/paths/Projects/delete-v2-projects-uuid-partners.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

[Task Link](https://gfw.atlassian.net/browse/TM-840)

[TM-840] allow project monitoring partners

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php

Fix sending correct value to coordinate system validator

[TM-973] fix coordinate system validation

---

app/Http/Controllers/V2/User/IndexMyActionsController.php
app/Models/V2/Action.php
tests/V2/User/IndexMyActionsControllerTest.php

[Task Link](https://gfw.atlassian.net/browse/TM-840)

[TM-840] add condition when projectIds < 0

---

Makefile
app/Console/Commands/OneOff/SetVersionNameForSitePolygons.php
app/Http/Controllers/V2/Sites/IndexSitePolygonVersionsController.php
app/Http/Controllers/V2/Sites/ShowSitePolygonController.php
app/Http/Controllers/V2/Sites/SitePolygonDataController.php
app/Http/Controllers/V2/Sites/StoreSitePolygonNewVersionController.php
app/Http/Controllers/V2/Sites/UpdateSitePolygonActiveController.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
app/Models/V2/Projects/Project.php
app/Models/V2/Sites/SitePolygon.php
app/Models/V2/User.php
app/Services/PolygonService.php
config/database.php
database/migrations/2024_07_05_140225_alter_site_polygon_table_to_add_versioning_attributes.php
database/seeders/PolygonValidationSeeder.php
openapi-src/V2/definitions/SitePolygon.yml
openapi-src/V2/paths/Polygons/get-v2-site-polygon-uuid-versions.yml
openapi-src/V2/paths/Polygons/get-v2-site-polygon-uuid.yml
openapi-src/V2/paths/Polygons/post-v2-site-polygon-uuid-new-version.yml
openapi-src/V2/paths/Polygons/put-v2-site-polygon-uuid-make-active.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

[Task Link](https://gfw.atlassian.net/browse/TM-861)

[TM-861] add polygon version

---

app/Console/Commands/OneOff/FixDuplicateDemographics.php
app/Models/V2/Workdays/Workday.php
tests/Unit/Models/V2/Workdays/WorkdayTest.php

https://gfw.atlassian.net/browse/TM-1098
[FE PR](https://github.com/wri/wri-terramatch-website/pull/380)
This includes both some data cleaning in the BE (that should hopefully not really be necessary with the FE fix) and a script to fix up existing duplicated data.

[TM-1098] Address a problem with duplicate workday demographics

---

app/Models/Traits/SaveAuditStatusTrait.php

[Task Link](https://gfw.atlassian.net/browse/TM-1122)
Seems that Update request content keeps record of deleted questions

[TM-1122] handle null cases

---

app/Http/Controllers/AuthController.php
app/Http/Controllers/V2/Projects/ViewProjectMonitoringPartnersController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1139)
[Task Link](https://gfw.atlassian.net/browse/TM-1140)

[TM-1139, 1140] add verify invites to monitoring partners

---

app/Http/Controllers/V2/AuditStatus/GetAuditStatusController.php
database/migrations/2024_07_23_182608_alter_table_audit_statuses_column_comment.php

[Task Link](https://gfw.atlassian.net/browse/TM-1121)

[TM-1121] comments length in audit log not counted

---

app/Console/Commands/ParseGeomBoundariesProjects.php

https://gfw.atlassian.net/browse/TM-1079

[TM-1079] fix correct attribute for projects

---

app/Policies/Policy.php

[Task Link](https://gfw.atlassian.net/browse/TM-1150)

[TM-1150] add isNewRoleUser condition to isUser function

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Models/V2/Sites/SitePolygon.php
app/Services/PolygonService.php

[Task Link](https://gfw.atlassian.net/browse/TM-1130)

[TM-1130] adaptation of functions to polygon version

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1130)

[TM-1130] fix: add missing parameters to insertGeoJsonToDB

---

database/migrations/2024_07_29_134440_add_value_to_criteria_site.php

Add migration to add new attribute

[TM-1144] create attribute in criteria site

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Services/PolygonService.php

https://gfw.atlassian.net/browse/TM-1144

[TM-1144] add error description for data schema

---

app/Helpers/GeometryHelper.php
openapi-src/V2/definitions/V2TerrafundCriteriaData.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-1144

[TM-1144] add swagger definition for output validation

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Services/PolygonService.php
app/Validators/Extensions/Polygons/NotOverlapping.php

https://gfw.atlassian.net/browse/TM-1143 
Add oerlapping information

[TM-1143] store criteria site for overlapping

---

app/Validators/Extensions/Polygons/EstimatedArea.php
app/Validators/Extensions/Polygons/NotOverlapping.php

https://gfw.atlassian.net/browse/TM-1156
store data for estimated area

[TM-1156] Add data in criteria site for estimated area

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Validators/Extensions/Polygons/EstimatedArea.php
app/Validators/Extensions/Polygons/NotOverlapping.php

https://gfw.atlassian.net/browse/TM-1144

[TM-1144] add validation for null extra info

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Services/PolygonService.php

https://gfw.atlassian.net/browse/TM-1144

[TM-1144] reorder functions to get valid schema data for polygons

---

app/Models/V2/ProjectPitch.php

https://gfw.atlassian.net/browse/TM-1104

[TM-1146] Fix Pitch model if organization is null

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Services/PolygonService.php
tests/Unit/Validators/Extensions/PolygonValidatorsTest.php

[Task Link](https://gfw.atlassian.net/browse/TM-1136)

[TM-1136] fix: reassigning site uuid

---

app/Models/V2/Sites/SitePolygon.php
app/Services/PolygonService.php

[Task Link](https://gfw.atlassian.net/browse/TM-1130)
[Task Link](https://gfw.atlassian.net/browse/TM-1136)

[TM-1136,1130] save properties loaded

---

.github/workflows/pull-request.yml

[Task Link](https://gfw.atlassian.net/browse/TM-1181)

[TM-1181] fix: add docker-compose to github action

---

app/Http/Resources/V2/Forms/FormSubmissionResource.php
openapi-src/V2/definitions/FormSubmissionRead.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-1104

[TM-1104] include project pitch uuid in form submission request

---

app/Models/V2/Sites/SitePolygon.php

[Task Link](https://gfw.atlassian.net/browse/TM-1180)

[TM-1180] add default value

---

app/Helpers/GeometryHelper.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
app/Models/V2/Sites/SitePolygon.php

https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1179

[TM-1179] revert approved on update geom

---

app/Http/Controllers/V2/Sites/AdminIndexSitesController.php
app/Models/Site.php
app/Models/V2/Sites/Site.php

https://gfw.atlassian.net/browse/TM-1177

[TM 1177] polygon filter

---

app/Models/V2/User.php

Originally this was a feature but checking the code I discover that was a bug.
Please check the type of change your PR introduces:
Issue Number: [TM-1134](https://gfw.atlassian.net/browse/TM-1134)
[TM-1134]: https://gfw.atlassian.net/browse/TM-1134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-1134] search functionality exists but pointing to a wrong property

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php

https://gfw.atlassian.net/browse/TM-1174?focusedCommentId=30183

[TM-1174] get sitePolygon Uuids for active records

---

app/Http/Resources/V2/User/MeResource.php

[Task Link](https://gfw.atlassian.net/browse/TM-1204)

[TM-1204] add organisation to meAction by fetching it from db

---

app/Http/Resources/V2/Projects/ProjectResource.php
app/Http/Resources/V2/Sites/SiteResource.php
app/Models/V2/Projects/Project.php
app/Models/V2/Sites/Site.php
app/Models/V2/Workdays/Workday.php

https://gfw.atlassian.net/browse/TM-1155
[FE PR](https://github.com/wri/wri-terramatch-website/pull/433)

[TM-1155] Add a combined workday count metric.

---

app/Services/PythonService.php
resources/python/polygon-clip/app.py
resources/python/polygon-clip/requirements.txt

https://gfw.atlassian.net/browse/TM-1185

[TM-1185] add python script to clip overlapping polygons

---

app/Http/Resources/V2/User/MeResource.php
app/Models/V2/User.php

https://gfw.atlassian.net/browse/TM-1204
https://gfw.atlassian.net/browse/TM-1205

[TM-1024/1025] Re-instate the original myPrimaryOrganisation attribute.

---

app/Http/Controllers/V2/AuditStatus/DeleteAuditStatusController.php
app/Http/Resources/V2/AuditStatusResource.php
openapi-src/V2/paths/AuditStatus/delete-v2-audit-status.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

[Task Link](https://gfw.atlassian.net/browse/TM-1186)

[TM-1186] add controller to delete audit log

---

app/Exports/V2/BaseExportFormSubmission.php

https://gfw.atlassian.net/browse/TM-1203

[TM-1023] Format seedings in a more useful way.

---

config/wri/file-handling.php

[Task Link](https://gfw.atlassian.net/browse/TM-1200)

[TM-1200] remove upload file restriction size at code level

---

app/Models/Traits/HasReportStatus.php
app/StateMachines/UpdateRequestStatusStateMachine.php

[Task Link](https://gfw.atlassian.net/browse/TM-1220)

[TM-1220] update nothing report when approve

---

app/Helpers/CreateVersionPolygonGeometryHelper.php
app/Helpers/PolygonGeometryHelper.php
app/Http/Controllers/V2/Terrafund/TerrafundClipGeometryController.php
resources/python/polygon-clip/app.py

This fix two tickets:
1182 and 1185 
1182: fix the correct return of uuid of the new version of polygon created
1185: with the good uuid, we have the names of the edition

[TM-1182] return correct uuid

---

resources/python/polygon-clip/app.py

https://gfw.atlassian.net/browse/TM-1185
reduce redundant points

[TM-1185] reduce quantity of points for buffering

---

app/Http/Resources/V2/ProjectReports/ProjectReportResource.php

[Task Link](https://gfw.atlassian.net/browse/TM-1157)

[TM-1157] add local engagement description to resource

---

app/Http/Controllers/V2/Terrafund/TerrafundClipGeometryController.php

https://gfw.atlassian.net/browse/TM-1185

[TM-1185] run validation on fixing polygon overlaps

---

app/Http/Controllers/V2/Entities/AdminSoftDeleteEntityController.php

https://gfw.atlassian.net/browse/TM-1163

[TM-1163] Add some delete logging when an admin deletes an entity.

---

app/Http/Controllers/V2/Terrafund/TerrafundClipGeometryController.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php

https://gfw.atlassian.net/browse/TM-1230

[TM-1230] Delete all related records when removing a Polygon

---

app/Policies/V2/Nurseries/NurseryPolicy.php
app/Policies/V2/Nurseries/NurseryReportPolicy.php
app/Policies/V2/Projects/ProjectPolicy.php
app/Policies/V2/Projects/ProjectReportPolicy.php
app/Policies/V2/Sites/SitePolicy.php
app/Policies/V2/Sites/SiteReportPolicy.php

[Task Link](https://gfw.atlassian.net/browse/TM-1171)

fix: problem with comparing roles

---

app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php

https://gfw.atlassian.net/browse/TM-1230

[TM-1230] send correct variable as uuid

---

app/Http/Controllers/V2/User/AdminUserController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1251)

[TM-1251] add update to approval stage

---

app/Http/Controllers/V2/Nurseries/CreateNurseryWithFormController.php
app/Http/Controllers/V2/Sites/CreateSiteWithFormController.php

https://gfw.atlassian.net/browse/TM-1072

[TM-1072] Update the logic for report creation following further discussion with product

---

app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
openapi-src/V2/definitions/DeletedPolygonsResponse.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/Terrafund/delete-v2-terrafund-project-polygons.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-1198
add endpoint to delete multiple uuids

[TM-1198] bulk delete

---

app/Http/Controllers/V2/Exports/ExportAllMonitoredEntitiesController.php

[Jira Release](https://gfw.atlassian.net/projects/TM/versions/10236/tab/release-report-all-issues)

[RELEASE] Magnanimous Mahogany Hotfix 2024-08-23

---

resources/python/polygon-voronoi/app.py

https://gfw.atlassian.net/browse/TM-1210
Add buffer to voronoi values

[TM-1210] buffer voronoi

---

app/Http/Resources/V2/Projects/ProjectResource.php
app/Http/Resources/V2/Sites/SiteResource.php
app/Models/V2/Projects/Project.php
app/Models/V2/Sites/Site.php

https://gfw.atlassian.net/browse/TM-1211
FE PR: https://github.com/wri/wri-terramatch-website/pull/467

[TM-1211] add Hectares under restoration to project and site resources

---

app/Exports/V2/EntityExport.php

https://gfw.atlassian.net/browse/TM-1201

[TM-1201] remove boundary_geojson field from exports

---

app/Http/Controllers/V2/AuditStatus/GetAuditStatusController.php
app/Http/Resources/V2/AuditStatusResource.php
app/Models/DTOs/AuditStatusDTO.php

[Task Link](https://gfw.atlassian.net/browse/TM-1267)

[TM-1267] fix problem with comment duplication in audit log

---

app/Http/Controllers/V2/NurseryReports/AdminIndexNurseryReportsController.php
app/Http/Controllers/V2/ProjectReports/AdminIndexProjectReportsController.php
app/Http/Controllers/V2/SiteReports/AdminIndexSiteReportsController.php
app/Models/V2/Nurseries/NurseryReport.php
app/Models/V2/Projects/ProjectReport.php
app/Models/V2/Sites/SiteReport.php

https://gfw.atlassian.net/browse/TM-1190

[TM-1190] Add organisation filter for reports page

---

app/Exports/V2/BaseExportFormSubmission.php
app/Exports/V2/EntityExport.php
app/Http/Controllers/V2/Exports/ExportAllMonitoredEntitiesController.php
config/excel.php

[Task Link](https://gfw.atlassian.net/browse/TM-1195)

[TM-1195] Fix export reports on csv with accent issue

---

app/Http/Controllers/V2/Workdays/GetWorkdaysForEntityController.php
app/Models/V2/Disturbance.php
app/Models/V2/Invasive.php
app/Models/V2/Seeding.php
app/Models/V2/Stratas/Strata.php
app/Models/V2/TreeSpecies/TreeSpecies.php

https://gfw.atlassian.net/browse/TM-1263

[TM-1263] Don't return hidden resources from the get for entity controllers

---

app/Exports/V2/BaseExportFormSubmission.php

[Task Link](https://gfw.atlassian.net/browse/TM-1292)

[TM-1292] some exports has been generated

---

app/Exports/V2/BaseExportFormSubmission.php

[Nimble Neem Hotfix 2024-09-09](https://gfw.atlassian.net/projects/TM/versions/10240/tab/release-report-all-issues)

[RELEASE] Nimble Neem Hotfix 2024-09-09

---

app/Http/Controllers/V2/Exports/ExportImageController.php
app/Http/Controllers/V2/Files/Gallery/ViewNurseryGalleryController.php
app/Http/Controllers/V2/Files/Gallery/ViewProjectGalleryController.php
app/Http/Controllers/V2/Files/Gallery/ViewSiteGalleryController.php
app/Http/Controllers/V2/Files/UploadController.php
database/migrations/2024_09_09_192124_add_fields_to_media_table.php
openapi-src/V2/paths/Exports/post-v2-export-image.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-1237
Frontend PR: https://github.com/wri/wri-terramatch-website/pull/484

[TM-1237] Image Gallery Enhancement

---

app/Models/V2/Sites/SiteReport.php

https://gfw.atlassian.net/browse/TM-778

[TM-778] error searching report by site name

---

app/Http/Resources/V2/Projects/ProjectResource.php

[Task Link](https://gfw.atlassian.net/browse/TM-437)

[TM-437] feat: calculate restored trees for ppc

---

app/Http/Controllers/V2/Geometry/GeometryController.php
app/Http/Requests/V2/Geometry/StoreGeometryRequest.php
tests/V2/Geometry/GeometryControllerTest.php

https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1290
Adding the possibility to accept multiple sites in points. 
and the response is the same but grouped by site_id, f.e.:
[  {
"site_id": "d1b8eac3-e265-4bba-9c1a-151fa0963543",
"polygon_uuids": [
"f2030a98-a8b8-47a8-a2e9-ed0321a3b5cb",
"86b4a34f-917f-42cf-a3b1-59c49f3ad972",
"234196b8-38a8-498a-ad29-12a2707d1173",
"50694cbb-8384-4da0-9896-c00635742759"
],
"errors": {
"f2030a98-a8b8-47a8-a2e9-ed0321a3b5cb": [
{
"key": "OVERLAPPING_POLYGON",
"message": "The geometry must not overlap with other project geometry"
},
{
"key": "TOTAL_AREA_EXPECTED",
"message": "The project's total geometry must match the project's estimated area."
},
{
"key": "EXCEEDS_EST_AREA",
"message": "The est_area is bigger than 5", …

[TM-1290] add grouping points by sites

---

app/Http/Controllers/V2/MediaController.php
app/Http/Resources/V2/Files/Gallery/GalleryResource.php
openapi-src/V2/definitions/FileResource.yml
openapi-src/V2/definitions/UpdateMediaRequest.yml
openapi-src/V2/definitions/V2FileGallery.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/Media/patch-v2-media-project-mediaUuid.yml
openapi-src/V2/paths/Media/patch-v2-media-uuid.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-1238
Frontend PR: https://github.com/wri/wri-terramatch-website/pull/487

[TM-1238] Image attribute editor modal

---

app/Http/Controllers/V2/UserLocaleController.php
app/Http/Requests/V2/UserLocaleRequest.php
openapi-src/V2/paths/Users/post-v2-users-locale.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

[Task Link](https://gfw.atlassian.net/browse/TM-578)

[TM-578] change path for updating user locale

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-1197
To generate geojsons reports of the DB. 
2 endpoints, 1 download all polygons 2 download by framework

[TM-1197] add download by framework and all polygons in geojson

---

app/Http/Controllers/V2/Applications/AdminIndexApplicationController.php
app/Http/Controllers/V2/Nurseries/AdminIndexNurseriesController.php
app/Http/Controllers/V2/Organisations/AdminOrganisationController.php
app/Http/Controllers/V2/Organisations/OrganisationListingController.php
app/Http/Controllers/V2/Polygons/ViewSitesPolygonsForProjectController.php
app/Http/Controllers/V2/ProjectPitches/AdminIndexProjectPitchController.php
app/Http/Controllers/V2/ProjectPitches/IndexProjectPitchController.php
app/Http/Controllers/V2/Projects/AdminIndexProjectsController.php
app/Http/Controllers/V2/Projects/ViewProjectNurseriesController.php
app/Http/Controllers/V2/Projects/ViewProjectSitesController.php
app/Http/Controllers/V2/Sites/AdminIndexSitesController.php
app/Http/Controllers/V2/User/AdminUserController.php
app/Models/V2/Forms/Application.php
app/Models/V2/Nurseries/Nursery.php
app/Models/V2/Organisation.php
app/Models/V2/ProjectPitch.php
app/Models/V2/Projects/Project.php
app/Models/V2/Sites/Site.php
app/Models/V2/User.php

https://gfw.atlassian.net/browse/TM-1246

[TM-1253] Search refactor for TM-1253, TM-1254, TM-1255, TM-1256, TM-1257

---

app/Http/Controllers/V2/Entities/AdminSendReminderController.php
app/Models/Traits/SaveAuditStatusTrait.php
database/migrations/2024_09_17_101030_alter_audit_statuses_table_type_new_column_reminder.php

[Task Link](https://gfw.atlassian.net/browse/TM-1284)

[TM-1284] save reminder in audit status log

---

app/Http/Controllers/V2/AuditStatus/StoreAuditStatusController.php
app/Http/Controllers/V2/Entities/SubmitEntityWithFormController.php
app/Jobs/V2/SendProjectManagerJob.php
app/Mail/EntityStatusChange.php
app/Mail/ProjectManager.php
database/seeders/LocalizationKeysTableSeeder.php

[Task Link](https://gfw.atlassian.net/browse/TM-1229)

[TM-1229] feat: generate email notification to project managers

---

database/seeders/LocalizationKeysTableSeeder.php

[Task Link](https://gfw.atlassian.net/browse/TM-1284)

[TM-1284] change subject to reminder notification

---

app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php

Add validator and fix return messages

[TM-1291] add validate polygon and correct message

---

app/Services/PolygonService.php

https://gfw.atlassian.net/browse/TM-1332
This change will prevent to insert any site_id that dont exists in v2_sites. 
This change will affect the uploads of files.

[TM-1332] rollback if no site id

---

app/Http/Resources/V2/ProjectReports/ProjectReportResource.php
app/Http/Resources/V2/SiteReports/SiteReportResource.php
app/Models/V2/Projects/ProjectReport.php
app/Models/V2/Sites/SiteReport.php

[Task Link](https://gfw.atlassian.net/browse/TM-1299)

[TM-1299] add new fields to resource

---

app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/CountriesController.php
app/Http/Controllers/V2/Dashboard/GetJobsCreatedController.php
app/Http/Controllers/V2/Dashboard/GetProjectsController.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php
app/Http/Controllers/V2/Dashboard/ViewRestorationStrategyController.php
app/Http/Controllers/V2/Dashboard/ViewTreeRestorationGoalController.php
openapi-src/V2/paths/Dashboard/get-v2-dashboard-active-countries.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-active-projects.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-countries.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-get-bbox-project.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-get-polygons-statuses.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-get-polygons.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-get-projects.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-jobs-created.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-restoration-strategy.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-top-trees-planted.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-total-section-header.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-tree-restoration-goal.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-volunteers-survival-rate.yml
resources/docs/swagger-v2.yml

[TM-1300] update all endpoints to new filters

---

openapi-src/V2/definitions/V2FileGallery.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-1306

[TM-1306] add name to file gallery definition

---

database/migrations/2024_10_03_132645_change_hectares_to_restore_goal_type_in_v2_sites.php

https://gfw.atlassian.net/browse/TM-1335

[TM-1335] update hectares type in sites table

---

app/Exports/V2/BaseExportFormSubmission.php

[Task Link](https://gfw.atlassian.net/browse/TM-1357)

[TM-1357] remove unnecessary json_encode

---

app/Exports/V2/BaseExportFormSubmission.php
app/Exports/V2/EntityExport.php
app/Http/Controllers/V2/Exports/ExportAllMonitoredEntitiesController.php
config/excel.php

[Task Link](https://gfw.atlassian.net/browse/TM-1357)

[TM-1357] Quotation marks around fields within exports

---

app/Http/Resources/V2/FundingProgrammes/FundingProgrammeLiteResource.php
app/Http/Resources/V2/FundingProgrammes/FundingProgrammeResource.php
app/Models/V2/FundingProgramme.php
database/migrations/2024_10_03_114200_add_location_id_column_to_funding_programmes_table.php
database/seeders/FundingProgrammesLocationsTableSeeder.php

[Task link](https://gfw.atlassian.net/browse/TM-582)

[TM-582] add location_id to translat

---

app/Http/Resources/V2/Forms/FormResource.php
app/Models/V2/Forms/Form.php
database/migrations/2024_10_07_143020_add_translation_submission_message_id.php
database/seeders/FormsSubmissionMessageTableSeeder.php

[Task Link](https://gfw.atlassian.net/browse/TM-1142)

[TM-1142] add form submission message translation

---

app/Http/Controllers/V2/FundingProgramme/AdminFundingProgrammeController.php
database/migrations/2024_10_07_104200_alter_location_id_in_funding_programmes_table.php

[Task link](https://gfw.atlassian.net/browse/TM-582)

[TM-582] funding programme location translated

---

app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php

https://gfw.atlassian.net/browse/TM-1341

[TM-1341] Add filters for dashboard endpoint

---

app/Http/Controllers/V2/Dashboard/ViewProjectController.php
openapi-src/V2/paths/Dashboard/get-v2-dashboard-frameworks.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-1341

[TM-1341] start up endpoint to get frameworks dynamically

---

app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php
openapi-src/V2/definitions/DashboardTotalSectionHeaderCountryData.yml
openapi-src/V2/definitions/DashboardTotalSectionHeaderCountryResponse.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-total-section-header-country.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

add endpoint to get specific data for country popup

[TM-1343] endpoint to get data for popup country

---

openapi-src/V2/definitions/DashboardProjectAvailableResponse.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-view-project-list.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

Add endpoint to get the list of projects visible

[TM-1343] add endpoint list projects

---

app/Http/Controllers/V2/Dashboard/ViewTreeRestorationGoalController.php

https://gfw.atlassian.net/browse/TM-1342

[TM-1342] use approved statuses for dashboard controller

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php

[TM-1344] add hectares under restoration

---

app/Helpers/TerrafundDashboardQueryHelper.php

https://gfw.atlassian.net/browse/TM-1341

[TM-1341] add filter for frameworks

---

app/Console/Commands/OneOff/UpdatePPCDueDatesCommand.php

[TM-1310] update logic to due_at

---

app/Console/Commands/OneOff/UpdatePPCDueDatesCommand.php

[Task Link](https://gfw.atlassian.net/browse/TM-1310)

[TM-1310] update due at

---

app/Console/Commands/OneOff/UpdatePPCDueDatesCommand.php
app/Models/Traits/HasWorkdays.php

[Task Link](https://gfw.atlassian.net/browse/TM-1368)

[TM-1368] complement logic to sumTotalWorkDaysAmount function

---

app/Services/PolygonService.php

Validate props for creating version

[TM-1301] add validator for dates

---

app/Http/Controllers/V2/Dashboard/ProjectProfileDetailsController.php

https://gfw.atlassian.net/browse/TM-1407

[TM-1407] include framework

---

database/migrations/2024_10_28_143000_change_indicator_id_to_indicator_slug_to_indicator_tables.php
database/migrations/2024_10_28_150000_add_timestamps_to_indicator_tables.php
database/migrations/2024_10_28_153000_add_uniqueness_constraint_to_indicator_tables.php

[Task Link](https://gfw.atlassian.net/browse/TM-1379)

[TM-1479] changes columns to table indicators

---

database/migrations/2024_10_28_192049_modify_landscape_column_in_v2_projects_table.php
database/seeders/InsertLandscapeData.php
resources/seeds/uuid-by-landscape.csv

Remove enum for landscape field. 
Add seeder to populate data from CSV

[TM-1366] insert landscape data, create seeder and migration

---

app/Http/Controllers/V2/Dashboard/TopProjectsAndTopTreeSpeciesController.php
openapi-src/V2/definitions/DashboardTopPlantedTree.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-1407?focusedCommentId=33321

[TM-1407] add organization in response for top trees planted controller

---

app/Console/Commands/OneOff/GenerateBackDatedReportsEnterprisesCommand.php
app/Console/Commands/OneOff/SeedScheduledJobsHbfEnterprises.php
app/Console/Commands/OneOff/SeedScheduledJobsHbfEnterprisesCommand.php

[Task Link](https://gfw.atlassian.net/browse/TM-1353)

[TM-1353] Add in logic for the generation of HBF and TerraFund Enterprise Reporting Tasks

---

app/Console/Commands/DeleteDummyBufferedPolygons.php

https://gfw.atlassian.net/browse/TM-1397

[TM-1397] start up command to delete dummy buffered polygons of a site

---

app/Http/Controllers/V2/Exports/GeneratePreSignedURLDownloadReportController.php
openapi-src/V2/paths/Exports/get-v2-admin-entity-presigned-url-framework.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

[Task Link](https://gfw.atlassian.net/browse/TM-1434)

Tm 1434 unable to download reports admin

---

app/Http/Controllers/V2/User/AdminUserController.php
app/Http/Requests/V2/User/UpdateUserRequest.php
app/Http/Resources/V2/User/UserResource.php
app/Models/V2/User.php
tests/V2/Users/AdminUserControllerTest.php

https://gfw.atlassian.net/browse/TM-1384
[v3 PR](https://github.com/wri/terramatch-microservices/pull/10)
[FE PR](https://github.com/wri/wri-terramatch-website/pull/613)

[TM-1384] User frameworks

---

app/Http/Controllers/V2/Dashboard/TopProjectsAndTopTreeSpeciesController.php
app/Jobs/Dashboard/RunTopTreesJob.php
app/Services/Dashboard/RunTopTreesService.php

[Task Link](https://gfw.atlassian.net/browse/TM-1436)

[TM-1436] add delayed job for top trees controller

---

app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Jobs/Dashboard/RunActiveCountriesTableJob.php
app/Services/Dashboard/RunActiveCountriesTableService.php

https://gfw.atlassian.net/browse/TM-1437

[TM-1437] dashboard active countries controller moved to job

---

app/Http/Controllers/V2/Exports/ExportAllProjectDataAsProjectDeveloperController.php
app/Jobs/ExportAllProjectDataAsProjectDeveloperJob.php
app/Services/ExportAllProjectDataAsProjectDeveloperService.php
tests/V2/Exports/ExportEntitiesAsProjectDeveloperControllerTest.php

[Task Link](https://gfw.atlassian.net/browse/TM-1417)

[TM-1417] add delayed job and cache to export project endpoint

---

app/Jobs/Dashboard/RunActiveCountriesTableJob.php

https://gfw.atlassian.net/browse/TM-1437

[TM-1437] send active countries data in payload

---

app/Http/Controllers/AuthController.php
app/Http/Controllers/V2/Projects/CreateProjectInviteController.php
app/Http/Requests/ConfirmCreateUserRequest.php
app/Mail/V2ProjectInviteReceived.php
openapi-src/V2/definitions/UserCreateComplete.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/Auth/put-auth-complete-signup.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api.php

[Task Link](https://gfw.atlassian.net/browse/TM-1289)

[TM-1289] add request to create user after inviting monitoring partner

---

app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Resources/V2/Dashboard/JobsCreatedResource.php
app/Http/Resources/V2/Dashboard/ViewTreeRestorationGoalResource.php
app/Services/Dashboard/JobsCreatedService.php
app/Services/Dashboard/RunActiveCountriesTableService.php
app/Services/Dashboard/RunHectaresRestoredService.php
app/Services/Dashboard/RunTopTreesService.php
app/Services/Dashboard/RunTotalHeaderService.php
app/Services/Dashboard/RunVolunteersAverageService.php
app/Services/Dashboard/TreeRestorationGoalService.php
openapi-src/V2/definitions/DashboardActiveCountriesData.yml
openapi-src/V2/definitions/DashboardJobsCreatedData.yml
openapi-src/V2/definitions/DashboardTreeRestorationGoalResponse.yml
openapi-src/V2/definitions/DashboardVolundteersSurvivalRateData.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-1426

[TM-1426] Optimize dashboard endpoints

---

app/Http/Controllers/V2/Dashboard/ProjectProfileDetailsController.php
app/Http/Resources/V2/Dashboard/ProjectProfileDetailsResource.php

https://gfw.atlassian.net/browse/TM-1407

[TM-1407] add files to projectdetail controller response for dashboard

---

app/Services/Dashboard/RunHectaresRestoredService.php
database/migrations/2024_11_06_202937_update_indicator_table_schemas.php

While working on implementing the indicator table schemas in the v3 codebase, I found some problems with the tables as currently implemented. See conversation here: https://werestore.slack.com/archives/C06A0BBCFUH/p1730924605503189

[TM-1451] Indicator table schemas

---

app/Console/Commands/CreateServiceAccount.php
config/wri/permissions.php

https://gfw.atlassian.net/browse/TM-1451

[TM-1451] Set up research service account role.

---

app/Console/Commands/BulkUpdateSiteReportDates.php

php artisan sitereports:bulk-update-dates /home/SITE_REPORT_DUE_DATES.csv

[TM-1477] update due date site reports

---

app/Exports/V2/OrganisationsExport.php

[Task Link](https://gfw.atlassian.net/browse/TM-1457)

[TM-1457] Optimized query with select to retrieve only necessary fields

---

app/Http/Controllers/V2/Dashboard/ViewProjectController.php
app/Models/V2/User.php

https://gfw.atlassian.net/browse/TM-1486

[TM-1486] dashboard access for terrafund and super admins

---

app/Http/Controllers/V2/Dashboard/ViewProjectController.php
app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php

https://gfw.atlassian.net/browse/TM-1489

[TM-1489] rollback dashboard funder and government permissions

---

app/Exports/V2/OrganisationsExport.php
app/Http/Controllers/V2/Organisations/AdminExportOrganisationsController.php
app/Jobs/ExportAllOrganisationsJob.php
app/Services/ExportAllOrganisationsService.php

[Task Link](https://gfw.atlassian.net/browse/TM-1457)

[TM-1457] add delayed job to organisations export

---

app/Http/Requests/V2/File/UploadRequest.php
config/wri/file-handling.php

[Task Link](https://gfw.atlassian.net/browse/TM-1456)

[TM-1456] add docx and bin to mimes types

---

app/Http/Resources/V2/Projects/ProjectResource.php
app/Models/V2/Projects/Project.php
app/Models/V2/Sites/SiteReport.php
tests/Unit/Models/V2/Projects/ProjectTest.php

[Task Link](https://gfw.atlassian.net/browse/TM-1474)

[TM-1474] approved filter to high level metrics in all entities

---

app/Helpers/GeometryHelper.php
app/Models/V2/Sites/CriteriaSite.php
app/Models/V2/Sites/CriteriaSiteHistoric.php
app/Services/PolygonService.php
database/migrations/2024_11_22_161557_remove_softdeletes_from_criteria_site.php
database/migrations/2024_11_22_161611_create_criteria_site_historic_table.php

add migration to delete soft delete from criteria_site and create criteria_site_historic. 
Also add on create criteria_site delete previous and copy it to criteria_site_historic.

[TM-1503] criteria historic

---

app/Http/Controllers/V2/Terrafund/TerrafundClipGeometryController.php

If no job created return message instead of fail

[TM-1461] check if job is created for fix

---

app/Http/Resources/V2/Dashboard/ProjectProfileDetailsResource.php
app/Models/Traits/HasProjectCoverImage.php

https://gfw.atlassian.net/browse/TM-1528

[TM-1528] send cover image for project in dashboard

---

app/Models/V2/Projects/ProjectReport.php
app/Models/V2/Sites/SiteReport.php
config/wri/linked-fields.php
database/migrations/2024_12_06_182649_add_report_fields_for_project_and_site_report.php

https://gfw.atlassian.net/browse/TM-1542

[TM-1542] Add New Fields to Project + Site Reports

---

app/Jobs/SendDailyDigestNotificationsJob.php

[Task Link](https://gfw.atlassian.net/browse/TM-1564)

[TM-1564] change logic

---

app/Jobs/SendDailyDigestNotificationsJob.php

[Task Link](https://gfw.atlassian.net/browse/TM-1564)

[TM-1564] add validation to verify if exist project

---

config/wri/linked-fields.php

[Task Link](https://gfw.atlassian.net/browse/TM-1542)

[TM-1542] change input type for pct_survival_to_date

---

app/Http/Controllers/V2/MonitoredData/GetPolygonsIndicatorAnalysisController.php
resources/python/polygon-indicator/requirements.txt

update requirements file

---

app/Console/Commands/OneOff/PopulateTreeSpeciesResearch.php
database/migrations/2024_12_16_200032_allow_null_infraspecific_epithet.php

One more change to the taxonomic backbone table.

[TM-1400] Allow null in infraspecific_epithet.

---

app/Http/Controllers/V2/MonitoredData/GetPolygonsIndicatorAnalysisController.php
app/Http/Controllers/V2/MonitoredData/RunIndicatorAnalysisController.php
app/Jobs/RunIndicatorAnalysisJob.php
app/Services/RunIndicatorAnalysisService.php

[Task Link](https://gfw.atlassian.net/browse/TM-1466)

[TM-1466] remove cached functinality from Redis

---

app/Console/Commands/OneOff/AssociateExactMatchTrees.php

https://gfw.atlassian.net/browse/TM-1579

[TM-1579] A script to update v2_tree_species with a taxon_id when there is an exact name match.

---

app/Http/Resources/V2/ProjectReports/ProjectReportResource.php
app/Http/Resources/V2/SiteReports/SiteReportResource.php

[Task Link](https://gfw.atlassian.net/browse/TM-1562)

[TM-1562] add new fields to resources

---

app/Mail/PolygonOperationsComplete.php

[Task Link](https://gfw.atlassian.net/browse/TM-1583)

[TM-1583] fix email polygon validation link

---

app/Models/Traits/UsesLinkedFields.php
app/Models/V2/TreeSpecies/TreeSpecies.php

https://gfw.atlassian.net/browse/TM-1581

[TM-1581] Improve BE mechanics for updating tree collections.

---

app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php
app/Jobs/Dashboard/RunTotalHeaderJob.php

https://gfw.atlassian.net/browse/TM-1586

[TM-1586] include the updated date in redis for dashboard

---

app/Http/Resources/V2/Projects/ProjectResource.php
app/Models/V2/Projects/Project.php
database/migrations/2025_01_09_200057_add_cohort_to_v2_projects_table.php

https://gfw.atlassian.net/browse/TM-1620

[TM-1620] add cohort field in v2 project table

---

app/Models/V2/ScheduledJobs/TaskDueJob.php

[Task Link](https://gfw.atlassian.net/browse/TM-1298)

[TM-1298] add validation before creating a reporting task

---

app/Console/Commands/OneOff/GenerateBackDatedReportsEnterprisesCommand.php
app/Models/V2/Projects/Project.php
app/Models/V2/ScheduledJobs/TaskDueJob.php
database/factories/V2/Nurseries/NurseryFactory.php
database/factories/V2/Projects/ProjectFactory.php
database/factories/V2/Sites/SiteFactory.php
tests/Unit/Models/V2/ScheduledJobs/ScheduledJobsTest.php

[Task Link](https://gfw.atlassian.net/browse/TM-1621)

[TM-1621] do not generate reports for started entities

---

app/Http/Controllers/V2/Reports/NothingToReportReportController.php
app/Http/Resources/V2/Tasks/TaskReportResource.php
app/Models/V2/Nurseries/NurseryReport.php
app/Models/V2/Projects/ProjectReport.php
app/Models/V2/Sites/SiteReport.php
openapi-src/V2/definitions/V2TaskActionRead.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-1624
[FE PR](https://github.com/wri/wri-terramatch-website/pull/808)

[TM-1624] Improvements to the API response for nothing to report action.

---

app/Helpers/TerrafundDashboardQueryHelper.php

https://gfw.atlassian.net/browse/TM-1625?focusedCommentId=36291

[TM-1625] remove option from cohort filter in dashboard (#653)

---

app/Http/Resources/V2/TreeSpecies/TreeSpeciesTransformer.php

https://gfw.atlassian.net/browse/TM-1602?focusedCommentId=36355

[TM-1603] add where clause to filter specifically by site report class

---

app/Helpers/RestorationByEcoregionHelper.php
app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Controllers/V2/MonitoredData/GetPolygonsIndicatorAnalysisController.php
app/Http/Controllers/V2/MonitoredData/GetPolygonsIndicatorAnalysisVerifyController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1575)

[TM-1575] add condition to get approved polygons

---

app/Http/Controllers/V2/Entities/GetRelationsForEntityController.php

https://gfw.atlassian.net/browse/TM-1602?focusedCommentId=36395

[TM-1602] include related data from seeding table

---

app/Console/Commands/OneOff/SetDefaultConditionalValuesForFormQuestions.php
app/Exceptions/Handler.php
app/Http/Resources/V2/Forms/FormQuestionResource.php
app/Models/V2/Forms/FormQuestion.php
database/migrations/2025_01_23_163905_add_is_parent_conditional_default_value.php

[Task Link](https://gfw.atlassian.net/browse/TM-1629)

[TM-1629] address comments with conditionals

---

app/Http/Controllers/V2/Entities/GetRelationsForEntityController.php

https://gfw.atlassian.net/browse/TM-1601?focusedCommentId=36456

[TM-1603] avoid duplicated taxon_id in initial list

---

app/Mail/ReportReminder.php
database/seeders/LocalizationKeysTableSeeder.php

[Task Link](https://gfw.atlassian.net/browse/TM-1326)

TM-1326] update remider emails

---

app/Policies/V2/UserPolicy.php

[Task Link](https://gfw.atlassian.net/browse/TM-1637)

[TM-1637] allow framework admins to create edit users

---

app/Http/Resources/V2/Projects/ProjectResource.php

https://gfw.atlassian.net/browse/TM-1639

[TM-1639] Include the detailed intervention types field on project responses

---

app/Mail/ReportReminder.php

[Task Link](https://gfw.atlassian.net/browse/TM-1326)

[TM-1326] fix: correct site name retrieval using where()->value()

---

app/Http/Controllers/V2/Exports/ProjectAdminExportController.php
app/Jobs/V2/GenerateProjectAdminEntityExportJob.php
openapi-src/V2/paths/Exports/get-v2-admin-entity-export-framework-pm.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

[Task Link](https://gfw.atlassian.net/browse/TM-1657)

[TM-1657] add export manager filter

---

app/Http/Controllers/V2/Entities/GetAggregateReportsController.php

https://gfw.atlassian.net/browse/TM-1608

[TM-1608] include frameworks in agregate data endpoint

---

database/migrations/2025_02_06_232635_remove_old_demographics_columns.php

https://gfw.atlassian.net/browse/TM-1682

[TM-1682] Remove stale demographic columns / tables.

---

app/Console/Commands/OneOff/CleanReportsConditionalDataAfterApproval.php
app/Models/Traits/HasReportStatus.php
app/Models/Traits/UsesLinkedFields.php

[Task Link](https://gfw.atlassian.net/browse/TM-1662)

[TM-1662] clean up reports data after approval

---

app/Jobs/SendDailyDigestNotificationsJob.php
app/Mail/TaskDigestMail.php

[Task Link](https://gfw.atlassian.net/browse/TM-1683)

[TM-1683] update sendDailyDigestNotificationJob for project mangers

---

app/Http/Resources/V2/ImpactStory/ImpactStoryResource.php

https://gfw.atlassian.net/browse/TM-1702

[TM-1702] include media in impact story resource

---

app/Http/Controllers/V2/Forms/StoreFormController.php
app/Http/Resources/V2/Forms/FormQuestionResource.php
app/Models/V2/Forms/FormQuestion.php
database/migrations/2025_02_12_150200_add_min_character_limit_field.php

[Task Link](https://gfw.atlassian.net/browse/TM-532)

[TM-532] add fields to formQuestion to limit option

---

app/Http/Controllers/V2/Exports/ExportProjectEntityAsProjectDeveloperController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1744)

[TM-1744] remove JSON_PRETTY_PRINT param

---

app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Controllers/V2/ImpactStory/ImpactStoryController.php
app/Http/Requests/V2/ImpactStories/StoreImpactStoryRequest.php
app/Policies/V2/ImpactStoryPolicy.php
openapi-src/V2/paths/ImpactStories/get-v2-impact-stories-id.yml
openapi-src/V2/paths/ImpactStories/get-v2-impact-stories.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

https://gfw.atlassian.net/browse/TM-1703

[TM-1703] Impact Story Dashboard

---

app/Console/Commands/SendWeeklyPolygonUpdateNotifications.php
app/Console/Kernel.php
app/Http/Controllers/V2/AuditStatus/StoreAuditStatusController.php
app/Http/Controllers/V2/Auditable/UpdateAuditableStatusController.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
app/Jobs/SendWeeklyPolygonUpdateNotificationsJob.php
app/Mail/PolygonUpdateNotification.php
app/Models/V2/PolygonUpdates.php
database/migrations/2025_02_17_022432_create_polygon_updates_table.php
database/seeders/LocalizationKeysTableSeeder.php
resources/views/Emails/master.blade.php

[Task Link](https://gfw.atlassian.net/browse/TM-1277)

[TM-1277] add email polygon updates

---

database/seeders/LocalizationKeysTableSeeder.php

[Task Link](https://gfw.atlassian.net/browse/TM-1277)

[TM-1277] email style fix

---

app/Http/Controllers/V2/ImpactStory/ImpactStoryController.php
app/Http/Resources/V2/ImpactStory/ImpactStoryResource.php

https://gfw.atlassian.net/browse/TM-1704

[TM-1704] Impact Story List

---

app/Mail/PolygonUpdateNotification.php
database/seeders/LocalizationKeysTableSeeder.php

[Task Link](https://gfw.atlassian.net/browse/TM-1277)

[TM-1277] fix polygon update email logic and display

---

app/Http/Requests/V2/Forms/UpdateFormRequest.php

[TM-532] custom form

---

app/Http/Resources/V2/ImpactStory/ImpactStoriesCollection.php
app/Http/Resources/V2/ImpactStory/ImpactStoryLiteResource.php

[Jira Release](https://gfw.atlassian.net/projects/TM/versions/10434/tab/release-report-all-issues)

[RELEASE] Youthful Yucca hotfix 2025 02 21

---

app/Console/Kernel.php

[Task Link](https://gfw.atlassian.net/browse/TM-1797)

[TM-1797] comment weekly call of polygon update notification

---

app/Http/Resources/V2/ProjectReports/ProjectReportResource.php
app/Models/V2/Projects/ProjectReport.php

https://gfw.atlassian.net/browse/TM-1416

[TM-1416] add renegerated trees on project reports resource

---

app/Helpers/TerrafundDashboardQueryHelper.php

https://gfw.atlassian.net/browse/TM-1789

[TM-1789] add filter to get impact stories with project uuid

---

app/Console/Kernel.php

[Jira Release](https://gfw.atlassian.net/projects/TM/versions/10500/tab/release-report-all-issues)

[RELEASE] Youthful Yucca hotfix 2025 02 25

---

app/Console/Commands/OneOff/UpdateProjectReportTreeCollections.php
app/Http/Controllers/V2/Entities/GetRelationsForEntityController.php
app/Http/Resources/V2/TreeSpecies/TreeSpeciesTransformer.php
config/wri/linked-fields.php

https://gfw.atlassian.net/browse/TM-1665

[TM-1665] Project report tree collection update

---

app/Http/Resources/V2/NurseryReports/NurseryReportResource.php
app/Http/Resources/V2/SiteReports/SiteReportResource.php
app/Models/V2/Nurseries/NurseryReport.php
app/Models/V2/Sites/SiteReport.php

[Task Link](https://gfw.atlassian.net/browse/TM-1058)

[TM-1058] add new properties to site and nursery reports

---

app/Console/Commands/OneOff/MigrateBeneficiariesToDemographics.php

https://gfw.atlassian.net/browse/TM-1719

[TM-1719] Fix totals calculations

---

app/Models/Traits/UsesLinkedFields.php

[Task Link](https://gfw.atlassian.net/browse/TM-1836)
Probably worth of a hot fix.

[TM-1836] fix array access by key

---

app/Models/Traits/UsesLinkedFields.php

https://gfw.atlassian.net/projects/TM/versions/10599/tab/release-report-all-issues

[RELEASE] Zealous Ziziphus hotfix 2026 03 07

---

app/Console/Commands/OneOff/UpdateSitePolygonsPlantStartField.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
app/Services/PolygonService.php

[Task Link](https://gfw.atlassian.net/browse/TM-1803)

[TM-1803] Update plantstart in SitePolygon using Site start_date

---

app/Models/Traits/UsesLinkedFields.php

[Task Link](https://gfw.atlassian.net/browse/TM-1853)

[TM-1853] add conditional to avoid request crash

---

app/Console/Commands/SendWeeklyPolygonUpdateNotifications.php
app/Helpers/PolygonNotificationMailHelper.php
app/Http/Controllers/V2/Auditable/UpdateAuditableStatusController.php
app/Jobs/SendWeeklyPolygonUpdateNotificationsJob.php
app/Mail/PolygonUpdateNotification.php
app/Models/V2/PolygonUpdates.php
database/migrations/2025_03_16_221928_add_fields_for_status_to_polygons_updates.php
database/seeders/LocalizationKeysTableSeeder.php

[Task Link](https://gfw.atlassian.net/browse/TM-1796)

[TM-1796] update weekly polygon notification email

---

app/Services/PolygonService.php

[Task Link](https://gfw.atlassian.net/browse/TM-1803)

[TM-1803] add conditional to add start date

---

app/Models/Traits/UsesLinkedFields.php
config/wri/linked-fields.php

https://gfw.atlassian.net/browse/TM-1853

[TM-1853] application data not saving

---

app/Http/Resources/V2/Applications/ApplicationResource.php
app/Http/Resources/V2/Stages/StageResource.php
openapi-src/V2/definitions/ApplicationRead.yml
openapi-src/V2/definitions/StageRead.yml
resources/docs/swagger-v2.yml

The ApplicationResource is a beast that was pulling in way too much information, and a lot of it duplicated. This doesn't fully trim it down, but it does cut the size of my sample application response from ~1.5MB to ~700KB, so I'm hoping this solves the issue on staging as well.
https://gfw.atlassian.net/browse/TM-1853

[TM-1853] Application resource size

---

app/Http/Resources/V2/Applications/ApplicationResource.php
app/Http/Resources/V2/FundingProgrammes/FundingProgrammeResource.php
openapi-src/V2/definitions/ApplicationRead.yml
openapi-src/V2/definitions/FundingProgrammeWithLiteStages.yml
openapi-src/V2/definitions/_index.yml
resources/docs/swagger-v2.yml

The previous pass wasn't good enough for staging to handle applications; hopefully this will do it.
https://gfw.atlassian.net/browse/TM-1853

[TM-1853] Remove another case of superfluously sending the full form.

---

app/Console/Kernel.php
app/Http/Controllers/V2/AuditStatus/StoreAuditStatusController.php
app/Http/Controllers/V2/Auditable/UpdateAuditableStatusController.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1796)

[TM-1796] change polygon update table to store primary_uuid

---

app/Http/Controllers/V2/AuditStatus/StoreAuditStatusController.php
app/Http/Controllers/V2/Auditable/UpdateAuditableStatusController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1796)

[TM-1796] change polygon update creation type on audit log

---

app/Http/Controllers/V2/Dashboard/ViewProjectController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1873)

[TM-1874] update logic to see the funder information

---

app/Http/Controllers/V2/Dashboard/ViewProjectController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1873)

[TM-1873] funder dashboard

---

app/Console/Commands/CacheDashboardDataCommand.php
app/Console/Kernel.php
app/Http/Controllers/V2/Dashboard/GetProjectsController.php
app/Jobs/Dashboard/RunActiveCountriesTableJob.php
app/Jobs/Dashboard/RunActiveProjectsJob.php
app/Jobs/Dashboard/RunHectaresRestoredJob.php
app/Jobs/Dashboard/RunJobsCreatedJob.php
app/Jobs/Dashboard/RunProjectsJob.php
app/Jobs/Dashboard/RunTopTreesJob.php
app/Jobs/Dashboard/RunTotalHeaderJob.php
app/Jobs/Dashboard/RunTreeRestorationGoalJob.php
app/Jobs/Dashboard/RunVolunteersAverageJob.php
app/Models/Traits/HasCacheParameter.php
app/Services/Dashboard/RunProjectsService.php

https://gfw.atlassian.net/browse/TM-1858

[TM-1858] include dynamic caching in dashboard

---

app/Http/Controllers/V2/Projects/ViewProjectSitesController.php
app/Http/Controllers/V2/Sites/AdminIndexSitesController.php
openapi-src/V2/definitions/SiteFullRead.yml
openapi-src/V2/definitions/V2SiteLiteRead.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/Projects/get-v2-projects-uuid-sites.yml
openapi-src/V2/paths/Sites/get-v2-sites-uuid.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2-old.yml
resources/docs/swagger-v2.yml
resources/docs/swagger.yml
routes/api_v2.php
tests/V2/Projects/ViewProjectSitesControllerTest.php
tests/V2/Sites/AdminIndexSitesControllerTest.php

https://gfw.atlassian.net/browse/TM-1893

[TM-1893] Bring back v2 project sites endpoint for Greenhouse.

---

.github/workflows/pull-request.yml
Makefile
README.md
docker-compose.yml
docker/php.Dockerfile
resources/python/polygon-voronoi/requirements.txt

https://gfw.atlassian.net/browse/TM-1898
I went down this rabbit hole because the current docker build wasn't working locally, and I had to blow away and rebuild my local docker containers today. Highlights:
* Update to using `docker compose` over the old (now unsupported) `docker-compose`
* Update to using `docker buildx bake` for the initial build of the compose file. 
* I had to bump the version of GDAL being created in the docker container to 3.5 to deal with some python dependency version issues. This _does not_ affect the EC2 boxes that are running our services on Amazon, and the unit tests pass, so I think this is OK for now.
* Use caching in github actions to try to avoid the full build on pull requests
* After the last commit, this is finally working. Note how the last run on …

[TM-1898] Improve docker

---

resources/python/polygon-indicator/app.py

https://gfw.atlassian.net/browse/TM-1909

[TM-1909] indicator output hectares

---

app/Http/Controllers/V2/Dashboard/ViewProjectController.php

https://gfw.atlassian.net/browse/TM-1918

[TM-1918] add polygon rule for allowing user to add polygons

---

app/Exports/V2/BaseExportFormSubmission.php

https://gfw.atlassian.net/browse/TM-1842

[TM-1842] Cover the new types of demographics in entity export.

---

app/Console/Commands/OneOff/MigrateLeadershipData.php

[Task Link](https://gfw.atlassian.net/browse/TM-1831)

[TM-1831] add missing property

---

app/Jobs/SendDailyDigestNotificationsJob.php

[Task Link](https://gfw.atlassian.net/browse/TM-1885)

[TM-1885] add conditional to check that pd are not considered pms

---

app/Console/Commands/UpdateSitePolygonValidityCommand.php
app/Http/Controllers/V2/Sites/AdminSitesPolygonController.php
app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
app/Http/Resources/SitePolygonLightResource.php
app/Jobs/NotifyGreenhouseJob.php
app/Jobs/RunSitePolygonsValidationJob.php
app/Models/V2/Sites/SitePolygon.php
app/Services/PolygonService.php
database/migrations/2025_04_04_200106_add_indexes_to_site_polygon_table.php
database/migrations/2025_04_04_202601_add_is_valid_to_site_polygon_table.php
openapi-src/V2/definitions/SitePolygon.yml
openapi-src/V2/paths/Entity/get-v2-entity-count.yml
openapi-src/V2/paths/Entity/get-v2-entity-polygon.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-1902

[TM-1902] improve site polygon load

---

app/Console/Commands/OneOff/MigratePitchDemographics.php
app/Console/Commands/Traits/DemographicsMigration.php
app/Models/V2/ProjectPitch.php
app/Models/V2/Projects/Project.php
config/wri/linked-fields.php

https://gfw.atlassian.net/browse/TM-1842

[TM-1842] Tweak to how we handle some of the dirty data in projects / pitches

---

app/Console/Commands/OneOff/UpdateFundingProgrammes.php
app/Http/Requests/V2/StoreFundingProgrammeRequest.php
app/Models/V2/FundingProgramme.php

https://gfw.atlassian.net/browse/TM-1866

[TM-1866] Update funding programme and framework related data.

---

app/Models/V2/ProjectPitch.php

https://gfw.atlassian.net/browse/TM-1892

[TM-1892] Fix the columns on Project Pitch that should be arrays.

---

app/Http/Resources/V2/Nurseries/NurseryResource.php
app/Http/Resources/V2/NurseryReports/NurseryReportResource.php
app/Http/Resources/V2/ProjectReports/ProjectReportResource.php
app/Http/Resources/V2/Projects/ProjectResource.php
app/Http/Resources/V2/SiteReports/SiteReportResource.php
app/Http/Resources/V2/Sites/SiteResource.php

https://gfw.atlassian.net/browse/TM-1774

[TM-1774] remove 'migrated' field from resource responses

---

app/Http/Controllers/V2/FinancialIndicators/DeleteFinancialIndicatorsController.php
app/Http/Controllers/V2/FinancialIndicators/GetFinancialIndicatorsController.php
app/Http/Controllers/V2/FinancialIndicators/StoreFinancialIndicatorsController.php
app/Http/Controllers/V2/FinancialIndicators/UpdateFinancialIndicatorsController.php
app/Http/Controllers/V2/Forms/StoreFormController.php
app/Http/Middleware/ModelInterfaceBindingMiddleware.php
app/Http/Requests/V2/Forms/UpdateFormRequest.php
app/Http/Requests/V2/StoreFinancialIndicatorsRequest.php
app/Http/Requests/V2/UpdateFinancialIndicatorsRequest.php
app/Http/Resources/V2/FinancialIndicatorsResource.php
app/Http/Resources/V2/Forms/FormQuestionResource.php
app/Http/Resources/V2/Organisation/OrganisationResource.php
app/Models/Organisation.php
app/Models/V2/FinancialIndicators.php
app/Models/V2/Forms/FormQuestion.php
app/Models/V2/Organisation.php
app/Models/V2/Projects/ProjectReport.php
app/Policies/V2/FinancialIndicatorsPolicy.php
config/wri/linked-fields.php
database/migrations/2025_04_15_132200_add_years_field.php
database/migrations/2025_04_16_154755_change_year_field_type_financial_indicators_table.php
openapi-src/V2/definitions/V2FinancialIndicatorsCreate.yml
openapi-src/V2/definitions/V2FinancialIndicatorsRead.yml
openapi-src/V2/definitions/V2FinancialIndicatorsUpdate.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

[Task Link](https://gfw.atlassian.net/browse/TM-1924)

[TM-1924] add model, definitions and controllers to financial indicators

---

app/Http/Controllers/V2/Entities/SubmitEntityWithFormController.php
app/Mail/ProjectManager.php

https://gfw.atlassian.net/browse/TM-1933

[TM-1933] Avoid send emails when site report is submitted

---

app/Http/Controllers/V2/Terrafund/TerrafundEditGeometryController.php
app/Services/PolygonService.php

[Task Link](https://gfw.atlassian.net/browse/TM-1966)

[TM-1966] remove changes

---

app/Http/Resources/SitePolygonLightResource.php

[Task Link](https://gfw.atlassian.net/browse/TM-1939)

[TM-1939] add calc_area in light resource

---

app/Helpers/GeometryHelper.php
app/Models/V2/Sites/SitePolygon.php

[Task Link](https://gfw.atlassian.net/browse/TM-1939)

[TM-1939] get extra attributes to polygon

---

app/Mail/PolygonUpdateNotification.php

[Task Link](https://gfw.atlassian.net/browse/TM-1989)

[TM-1989] remove properties types

---

app/Http/Resources/V2/Dashboard/ProjectProfileDetailsResource.php
app/Services/Dashboard/RunTotalHeaderService.php

https://gfw.atlassian.net/browse/TM-2012

[TM-2012] remove country references in some dashboard endpoint

---

app/Services/Dashboard/RunActiveCountriesTableService.php

https://gfw.atlassian.net/browse/TM-2021

[TM-2021] use new iso notation for active countries

---

app/Http/Controllers/V2/Geometry/GeometryController.php
app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Services/PolygonService.php
app/Services/PolygonValidationService.php
app/Validators/Extensions/Polygons/PlantStartDate.php
app/Validators/SitePolygonValidator.php
app/Validators/Validator.php

https://gfw.atlassian.net/browse/TM-2000

[TM-2000] add plant start date validation

---

app/Console/Commands/OneOff/ExportOldPPCDemographics.php
app/Models/Traits/HasDemographics.php

https://gfw.atlassian.net/browse/TM-1980

[TM-1980] Demographics updates for PPC

---

app/Http/Controllers/V2/MonitoredData/IndicatorEntitySlugExportController.php

[Task Link](https://gfw.atlassian.net/browse/TM-2046)

[TM-2046] fix: move slugMappings

---

app/Console/Commands/RunIndicatorAnalysisCommand.php
app/Helpers/RestorationByEcoregionHelper.php
app/Services/RunIndicatorAnalysisService.php
resources/python/polygon-indicator/app.py
resources/python/polygon-indicator/config.yaml

https://gfw.atlassian.net/browse/TM-2047

[TM-2047] ecoregion indicator

---

app/Models/Traits/HasDemographics.php

https://gfw.atlassian.net/browse/TM-2055

[TM-2055] Update logic on when we fall back to the parent attribute.

---

app/Http/Controllers/V2/FinancialIndicators/UpsertFinancialIndicatorsController.php

[Task Link](https://gfw.atlassian.net/browse/TM-1967)

[TM-1967] remove organisation type conditional

---

app/Mail/PolygonUpdateNotification.php

[Task Link](https://gfw.atlassian.net/browse/TM-2052)

[TM-2052] remove types to avoid TypeError

---

app/Http/Resources/V2/Applications/ApplicationLiteResource.php
openapi-src/V2/definitions/ApplicationLiteRead.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-2062

[TM-2062] Bring back some fields I thought were unused, but are needed in Admin

---

app/Console/Commands/BulkOrganisationImport.php
app/Console/Commands/BulkUserImport.php
app/Http/Controllers/AuthController.php
app/Mail/BulkUserCreation.php
app/Models/V2/Organisation.php
database/seeders/LocalizationKeysTableSeeder.php
openapi-src/V2/paths/Auth/get-auth-mail.yml
resources/docs/swagger-v2.yml

https://gfw.atlassian.net/browse/TM-2065

[TM-2065] Scripts to batch import organisations and users

---

app/Helpers/PolygonNotificationMailHelper.php
app/Mail/I18nMail.php
app/Mail/PolygonUpdateNotification.php
app/Services/Polyline.php

[Task Link](https://gfw.atlassian.net/browse/TM-1968)

[TM-1968] show hectare change in polygon updates

---

app/Helpers/TerrafundDashboardQueryHelper.php
app/Services/Dashboard/RunActiveProjectsService.php

https://gfw.atlassian.net/browse/TM-2036

[TM-2036] add additional attributes for active projects

---

app/Console/Commands/CreateProjectReportReminder.php
app/Mail/TerrafundReportReminder.php
database/seeders/LocalizationKeysTableSeeder.php
tests/Unit/Models/V2/ScheduledJobs/ScheduledJobsTest.php

[Task Link](https://gfw.atlassian.net/browse/TM-2082)

[TM-2082] update terrafund reminder email

---

app/Models/Traits/UsesLinkedFields.php

https://gfw.atlassian.net/browse/TM-2057

[TM-2057] allow clearing of non-required date fields in form validation

---

app/Services/Dashboard/TreeRestorationGoalService.php

https://gfw.atlassian.net/browse/TM-2101

[TM-2101] add visible to query in tree restoration

---

app/Console/Commands/UpdateV2ProjectShortNameBasedOnCsvCommand.php
app/Models/V2/Projects/Project.php
database/migrations/2025_06_01_200639_add_column_short_name_to_v2_projects.php

[Task Link](https://gfw.atlassian.net/browse/TM-2049)

[TM-2049] add project short_name column

---

app/Console/Commands/UpdateV2ProjectShortNameBasedOnCsvCommand.php

[Task Link](https://gfw.atlassian.net/browse/TM-2049)

[TM-2049] convert short code to uppercase

---

app/Models/V2/Demographics/DemographicCollections.php
app/Models/V2/Organisation.php
app/Models/V2/Projects/ProjectReport.php
config/wri/linked-fields.php

https://gfw.atlassian.net/browse/TM-1994

[TM-1994] Add new collections for Fundo Flora

---

app/Models/Traits/HasDemographics.php

https://gfw.atlassian.net/browse/TM-2054

[TM-2054] The detection of aggregate type / collection props needs to be a little smarter.

---

app/Http/Resources/SitePolygonLightResource.php

https://gfw.atlassian.net/browse/TM-2142

[TM-2142] include id in site polygon light resource

---

app/Console/Commands/RemovePasswordResetsCommand.php

[Task Link](https://gfw.atlassian.net/browse/TM-2150)

[TM-2150] don't delete reset password token before 7 days

---

app/Http/Resources/SitePolygonLightResource.php

add site_id for cards 
https://gfw.atlassian.net/browse/TM-2159

[TM-2159] add site_id in polygons data for cards

---

app/Services/PolygonService.php

https://gfw.atlassian.net/browse/TM-2189

[TM-2189] add grassland land use

---

app/Http/Controllers/V2/Dashboard/GetPolygonsController.php
openapi-src/V2/definitions/DashboardGetPolygonStatusResponse.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/Dashboard/get-v2-dashboard-get-polygons-statuses.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

Reverts wri/wri-terramatch-api#906

Revert "[TM-2139] remove endpoint for dashboard polygon statuses"

---

app/Console/Commands/ReassignMediaCollectionsCommand.php

https://gfw.atlassian.net/browse/TM-2115

[TM-2115] reassign media collection names command

---

app/Jobs/V2/GenerateProjectAdminEntityExportJob.php

[Task Link](https://gfw.atlassian.net/browse/TM-2119)

[TM-2119] add coditional to site-reports in admin export

---

app/Helpers/TerrafundDashboardQueryHelper.php

https://gfw.atlassian.net/browse/TM-2226

[TM-2226] use correct notation for dashboard lanscape filter

---

app/Http/Controllers/V2/Stages/IndexStageController.php
app/Http/Resources/V2/Stages/StageLiteResource.php
app/Http/Resources/V2/Stages/StagesLightCollection.php

[Task Link](https://gfw.atlassian.net/browse/TM-2218)

[TM-2218] add lite resource to stages

---

app/Console/Commands/UpdateSitePolygonCentroidsCommand.php
app/Helpers/GeometryHelper.php
app/Models/V2/PolygonGeometry.php
app/Models/V2/Sites/SitePolygon.php
database/migrations/2025_06_27_140329_add_lat_lng_to_site_polygons.php

https://gfw.atlassian.net/browse/TM-2205

[TM-2205] update create centroid

---

app/Models/V2/Organisation.php

[Task Link](https://gfw.atlassian.net/browse/TM-2111)

[TM-2111] change carbon credits fields integer -> boolean

---

app/Console/Commands/OneOff/ConvertProjectPipelinesCohortToJsonCommand.php
app/Console/Commands/OneOff/ConvertV2ProjectsCohortToJsonCommand.php
app/Helpers/TerrafundDashboardQueryHelper.php
app/Http/Controllers/V2/Dashboard/ActiveCountriesTableController.php
app/Http/Controllers/V2/Dashboard/ActiveProjectsTableController.php
app/Http/Controllers/V2/Dashboard/GetJobsCreatedController.php
app/Http/Controllers/V2/Dashboard/TotalTerrafundHeaderDashboardController.php
app/Http/Controllers/V2/Dashboard/VolunteersAndAverageSurvivalRateController.php
app/Http/Controllers/V2/Indicators/GetHectaresRestoredController.php
app/Http/Controllers/V2/Terrafund/TerrafundCreateGeometryController.php
app/Http/Requests/V2/ProjectPipelineRequest.php
app/Models/Traits/HasCacheParameter.php
app/Models/V2/ProjectPipeline.php
app/Models/V2/Projects/Project.php
database/migrations/2025_06_26_115815_convert_cohort_to_json_in_v2_projects_table.php
database/migrations/2025_06_26_115931_convert_cohort_to_json_in_project_pipelines_table.php
openapi-src/V2/definitions/ProjectPipeline.yml
openapi-src/V2/definitions/ProjectPipelinePost.yml

https://gfw.atlassian.net/browse/TM-2129

[TM-2129] from string to array conversion for cohort field

---

database/migrations/2025_07_01_232921_add_fields_disturbance_v2.php

[TM-2221] Add new fields disturbance

---

app/Http/Controllers/V2/FinancialReports/ExportFinancialReportController.php
app/Http/Requests/V2/FinancialReports/ExportFinancialReportRequest.php
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

[Task Link](https://gfw.atlassian.net/browse/TM-2146)

[TM-2146] add export funcionality

---

app/Console/Commands/CreateReportCommand.php
app/Http/Controllers/V2/FinancialIndicators/UpsertFinancialIndicatorsController.php
app/Http/Resources/V2/FinancialIndicatorsResource.php
app/Models/V2/FinancialReport.php

[Task Link](https://gfw.atlassian.net/browse/TM-2263)

[TM-2263] financial migrating to forms

---

app/Http/Controllers/AuthController.php
app/Http/Controllers/V2/Organisations/CreateOrganisationInviteController.php
app/Http/Requests/ConfirmCreateUserRequest.php
app/Http/Requests/V2/Organisations/CreateOrganisationInviteRequest.php
app/Http/Resources/V2/Organisation/OrganisationInviteResource.php
app/Mail/V2OrganisationInviteReceived.php
app/Models/V2/Organisation.php
app/Models/V2/Organisations/OrganisationInvite.php
app/Policies/V2/OrganisationPolicy.php
database/migrations/2025_07_10_195728_create_v2_organisation_invites_table.php
database/seeders/LocalizationKeysTableSeeder.php
openapi-src/V2/definitions/V2OrganisationInviteCreate.yml
openapi-src/V2/definitions/V2OrganisationInviteRead.yml
openapi-src/V2/definitions/_index.yml
openapi-src/V2/paths/Organisations/post-v2-organisations-uuid-invite.yml
openapi-src/V2/paths/_index.yml
resources/docs/swagger-v2.yml
routes/api_v2.php

[Task Link](https://gfw.atlassian.net/browse/TM-2268)

[TM-2268] add user invite to organization functionality

---

app/Console/Commands/UpdateSitePolygonValidityCommand.php
app/Http/Controllers/V2/Auditable/UpdateAuditableStatusController.php
app/Services/PolygonService.php

https://gfw.atlassian.net/browse/TM-2276

[TM-2276] plant start date validation can be excluded

---

app/Jobs/V2/GenerateProjectAdminEntityExportJob.php

[Task Link](https://gfw.atlassian.net/browse/TM-2241)

[TM-2241] get managedProjects to users

---

app/Console/Commands/V2PopulateMediaTypeCommand.php
database/migrations/2025_07_21_102635_remove_unnecessary_columns_from_media_table.php

[Task Link](https://gfw.atlassian.net/browse/TM-1901)

[TM-1901] add data to new field 'type'

---

app/Console/Commands/V2PopulateMediaTypeCommand.php
app/Observers/MediaObserver.php

[Task Link](https://gfw.atlassian.net/browse/TM-1901)

[TM-1901] Add special case for malformed mime_type in media type mapping

---

app/Console/Commands/CloseFundoFloraFundingProgrammesCommand.php
app/Console/Kernel.php

[Task Link](https://gfw.atlassian.net/browse/TM-2343)

[TM-2343] add command to disable fundo flora funding programmes

---

app/Helpers/RestorationByEcoregionHelper.php
app/Http/Controllers/V2/MonitoredData/GetPolygonsIndicatorAnalysisController.php
app/Http/Controllers/V2/MonitoredData/IndicatorEntitySlugExportController.php

[Task Link](https://gfw.atlassian.net/browse/TM-2378)

[TM-2378] update controller to get and export indicators

---

app/Console/Commands/UploadInvestmentCsvCommand.php
docker-compose.yml
imports/Investment splits.csv
imports/Investments.csv

[task link](https://gfw.atlassian.net/browse/TM-2315)

[TM-2315] Upload new records to the investments and investment splits tables

---

app/Models/Traits/UsesLinkedFields.php

https://gfw.atlassian.net/browse/TM-2397

[TM-2397] add validation from polygongeometry

---

app/Exports/V2/ApplicationExport.php

https://gfw.atlassian.net/browse/TM-2407

[TM-2407] Handle proj boundary differently now that it's a GeoJSON array instead of a string.

---

database/migrations/2025_08_22_053816_remove_planting_status_from_v2_reports_tables.php
database/migrations/2025_08_22_063800_add_planting_status_from_v2_reports_tables.php

https://gfw.atlassian.net/browse/TM-2374

[TM-2374] remove planting_status from v2_sites, v2_projects, and site_polygon

---

app/Helpers/GeometryHelper.php
app/Http/Controllers/V2/Geometry/GeometryController.php
app/Jobs/ProcessPolygonIndicatorsJob.php
app/Services/IndicatorUpdateService.php
app/Services/PythonService.php
resources/python/polygon-indicator/tree_cover_indicator.py

https://gfw.atlassian.net/browse/TM-2401

[TM-2401] docouple indicators analysis from polygons creation endpoint

---

app/Models/V2/FinancialIndicators.php

https://gfw.atlassian.net/projects/TM/versions/11622/tab/release-report-all-issues

[RELEASE] Majestic Malachite Hotfix 2025-09-04

---

app/Jobs/V2/SendEntityStatusChangeEmailsJob.php

[Task Link](https://gfw.atlassian.net/browse/TM-2442)

[TM-2442] Enable mails for financial reports

---

config/wri/linked-fields.php
database/migrations/2025_09_17_180934_add_ff_descriptions_to_project_pitches.php

https://gfw.atlassian.net/browse/TM-2485

[TM-2485] Add two new project pitch fields for Fundo Flora

---

app/Http/Controllers/V2/User/IndexMyActionsController.php
app/Jobs/RunIndexMyActionsJob.php
app/Services/MyActionsService.php
tests/V2/User/IndexMyActionsControllerTest.php

[Task Link](https://gfw.atlassian.net/browse/TM-2499)

[TM-2499] add delayed job for actions

---

app/Console/Commands/OneOff/AddFunfingTypeDataOrganisationToFinancialReport.php
app/Console/Commands/OneOff/RemoveDuplicationFinancialData.php
app/Models/V2/FinancialIndicators.php

[Task Link](https://gfw.atlassian.net/browse/TM-2480)

[TM-2480] add command for remove duplication financial data

---

app/Constants/PolygonFields.php
app/Services/PolygonService.php
app/Services/PolygonValidationService.php
app/Validators/Extensions/Polygons/PlantStartDate.php

https://gfw.atlassian.net/browse/TM-2500

[TM-2500] update validation plant start

---

app/Http/Controllers/V2/Forms/UpdateFormSubmissionStatusController.php

[Task Link](https://gfw.atlassian.net/browse/TM-2498)

[TM-2498] fix: application approval email sending

---

app/Console/Commands/MigrateSpecificSiteToProject.php
app/Console/Commands/OneOff/MigrateSpecificSiteToProject.php

[Task Link](https://gfw.atlassian.net/browse/TM-2490)

[TM-2490] add command for migrate site to a new project

---

app/Models/V2/Organisation.php
config/wri/linked-fields.php

[Task Link](https://gfw.atlassian.net/browse/TM-2538)

[TM-2538] add leadership relations

---

app/Http/Controllers/V2/Forms/UpdateFormSubmissionStatusController.php
app/Mail/FormSubmissionFeedbackReceived.php
database/seeders/LocalizationKeysTableSeeder.php

https://gfw.atlassian.net/projects/TM/versions/11787/tab/release-report-all-issues

[RELEASE] Opulent Opal Hotfix 20251006

---

app/Http/Controllers/V2/Terrafund/TerrafundClipGeometryController.php

https://gfw.atlassian.net/browse/TM-2537

[TM-2537] avoid N+1 query
